## Import Library

In [5]:
import pandas as pd

## Load Dataset

In [6]:
from pathlib import Path

base = Path.cwd()
if not (base / "LP and Course Mapping.xlsx").exists():
    base = base.parent  # root repo

lp_mapping = pd.read_excel(base / "LP and Course Mapping.xlsx", sheet_name=None)
resource_data = pd.read_excel(base / "Resource Data Learning Buddy.xlsx", sheet_name=None)

datasets = {**lp_mapping, **resource_data}
print("LP and Course Mapping:", lp_mapping.keys())
print("Resource Data Learning Buddy:", resource_data.keys())

LP and Course Mapping: dict_keys(['LP + Course', 'Learning Path', 'Course', 'Tutorials', 'Course Level'])
Resource Data Learning Buddy: dict_keys(['Learning Path Answer', 'Current Interest Questions', 'Current Tech Questions', 'Skill Keywords', 'Student Progress'])

In [7]:
# Pisahkan sheet ke variabel masing-masing
# LP and Course Mapping
lp_course = lp_mapping['LP + Course']
learning_path = lp_mapping['Learning Path']
course = lp_mapping['Course']
course_level = lp_mapping['Course Level']
tutorials = lp_mapping['Tutorials']

# Resource Data Learning Buddy
lp_answer = resource_data['Learning Path Answer']
interest_qs = resource_data['Current Interest Questions']
tech_qs = resource_data['Current Tech Questions']
skill_keywords = resource_data['Skill Keywords']
stud_progress = resource_data['Student Progress']

In [8]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())
    print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
0,AI Engineer,Belajar Dasar AI,Dasar,Taksonomi AI
1,AI Engineer,Belajar Dasar AI,Dasar,[Story] Machine Learning: Harapan menjadi keny...
2,AI Engineer,Belajar Dasar AI,Dasar,Rangkuman Kelas
3,AI Engineer,Belajar Dasar AI,Dasar,Tipe-Tipe Machine Learning
4,AI Engineer,Belajar Dasar AI,Dasar,Forum Diskusi

Shape: 7916 rows × 4 columns

Learning Path

   learning_path_id             learning_path_name
0                 1                    AI Engineer
1                 2              Android Developer
2                 3  Back-End Developer JavaScript
3                 4      Back-End Developer Python
4                 5                 Data Scientist

Shape: 13 rows × 2 columns

Course

,course_id,learning_path_id,course_name,course_level_str,hours_to_study
0,1,1,Belajar Dasar AI,1,10
1,2,1,Belajar Fundamental Deep Learning,3,110
2,3,1,Belajar Machine Learning untuk Pemula,2,90
3,4,1,Machine Learning Terapan,4,80
4,5,1,Membangun Proyek Deep Learning Tingkat Mahir,4,90

Shape: 75 rows × 5 columns

Tutorials

,tutorial_id,course_id,tutorial_title,Unnamed: 3,Unnamed: 4
0,1,1,Taksonomi AI,NaN,NaN
1,2,1,[Story] Machine Learning: Harapan menjadi keny...,NaN,NaN
2,3,1,Rangkuman Kelas,NaN,NaN
3,4,1,Tipe-Tipe Machine Learning,NaN,NaN
4,5,1,Forum Diskusi,NaN,NaN

Shape: 7771 rows × 5 columns

Course Level

   id course_level
0   1        Dasar
1   2       Pemula
2   3     Menengah
3   4        Mahir
4   5  Profesional

Shape: 5 rows × 2 columns

Learning Path Answer

,id,name,summary,description,course_difficulty,course_price,technologies,course_type,courseMeta,courseInfo
0,14,Belajar Fundamental Aplikasi Android,Pelajari skill Android dengan kurikulum terlen...,Android merupakan sistem operasi mobile dengan...,Menengah,PAID,Android,Picodiploma,"['140 Jam', '4,84', 'Menengah']","['107 Modul', '41.831 Siswa Terdaftar']"
1,32,Belajar Membangun LINE Chatbot,Belajar membuat chatbot yang menarik pada plat...,LINE merupakan platform komunikasi yang sangat...,Pemula,PAID,"Android,Chatbot,Web",Reguler,"['20 Jam', '4,89', 'Pemula']","['26 Modul', '15.478 Siswa Terdaftar']"
2,51,Belajar Membuat Aplikasi Android untuk Pemula,Buat aplikasi pertamamu pada Android Studio de...,Android merupakan sistem operasi mobile dengan...,Pemula,PAID,Android,Reguler,"['60 Jam', '4,87', 'Pemula']","['49 Modul', '116.344 Siswa Terdaftar']"
3,60,Memulai Pemrograman Dengan Java,Belajar bahasa Java buat kamu yang ingin mempe...,Java merupakan bahasa yang diciptakan oleh Jam...,Dasar,FREE,"Android,Multi Platform",Reguler,"['15 Jam', '4,86', 'Dasar']","['42 Modul', '80.316 Siswa Terdaftar']"
4,80,Memulai Pemrograman dengan Kotlin,"Pelajari dasar bahasa pemrograman, functional ...",Kotlin merupakan bahasa utama yang digunakan d...,"Dasar,Pemula",PAID,"Android,Multi Platform",Reguler,"['50 Jam', '4,84', 'Dasar - Pemula']","['132 Modul', '59.512 Siswa Terdaftar']"

Shape: 67 rows × 10 columns

Current Interest Questions

,question_desc,option_text,category
0,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
1,Mana kegiatan yang paling relate denganmu di p...,Baca atau lihat info viral dari berbagai sumber,Artificial Intelligence
2,Mana kegiatan yang paling relate denganmu di p...,Membersihkan kamar,Cloud Computing
3,Mana kegiatan yang paling relate denganmu di p...,Coret-coret atau menulis di buku,Web Development
4,"Jika sedang menghadapi masalah, cara mana yang...",Coba berbagai cara sampai menemukan solusinya,Mobile Development

Shape: 20 rows × 3 columns

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
0,Android,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Komponen yang menangani tampilan pengguna,Kelas untuk menyimpan data,Fungsi untuk menjalankan proses di latar belakang,Antarmuka untuk menghubungkan database,Komponen yang menangani tampilan pengguna
1,Android,beginner,Apa fungsi utama dari file AndroidManifest.xml?,Menyimpan data aplikasi,Mendefinisikan struktur dan metadata aplikasi,Mengatur tata letak UI,Mengelola dependensi proyek,Mendefinisikan struktur dan metadata aplikasi
2,Android,beginner,"Dalam konteks Android, apa yang dimaksud denga...",Komponen untuk menyimpan data,Mekanisme untuk navigasi antar Activity,Fungsi untuk menangani error,Framework untuk membuat UI,Mekanisme untuk navigasi antar Activity
3,Android,beginner,Apa perbedaan utama antara LinearLayout dan Re...,"LinearLayout hanya untuk orientasi vertikal, R...","LinearLayout mengatur elemen secara berurutan,...","LinearLayout untuk aplikasi sederhana, Relativ...","Tidak ada perbedaan, keduanya dapat digunakan ...","LinearLayout mengatur elemen secara berurutan,..."
4,Android,beginner,Apa fungsi dari metode onCreate() dalam sebuah...,Menghapus Activity,Menginisialisasi Activity dan memuat layout,Menjalankan proses di background,Mengatur animasi transisi,Menginisialisasi Activity dan memuat layout

Shape: 326 rows × 8 columns

Skill Keywords

   id     keyword
0   4  JavaScript
1   9        Java
2  14      Python
3  19      Kotlin
4  24         PHP

Shape: 5553 rows × 2 columns

Student Progress

,name,email,course_name,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
0,Dina Wijaya,dina.wijaya1@example.com,Belajar Membangun Aplikasi Android Native Bagi...,4,0,0,0,4.0,NaN,NaN,NaN
1,Irfan Halim,irfan.halim2@example.com,Belajar Membangun Aplikasi dengan Universal Wi...,10,0,0,0,76.0,NaN,NaN,NaN
2,Hana Pratama,hana.pratama3@example.com,Belajar Fundamental Aplikasi Android,107,1,0,0,1099.0,NaN,163.0,NaN
3,Dina Utama,dina.utama4@example.com,Belajar Fundamental Aplikasi Android,107,0,0,0,1099.0,NaN,163.0,NaN
4,Rafi Santoso,rafi.santoso5@example.com,Belajar Fundamental Aplikasi Android,107,55,0,0,1099.0,NaN,163.0,NaN

Shape: 271 rows × 11 columns

In [9]:
# Dictionary untuk looping
datasets = {
    "LP + Course": lp_course,
    "Learning Path": learning_path,
    "Course": course,
    "Course Level": course_level,
    "Tutorials": tutorials,
    "Learning Path Answer": lp_answer,
    "Current Interest Questions": interest_qs,
    "Current Tech Questions": tech_qs,
    "Skill Keywords": skill_keywords,
    "Student Progress": stud_progress
}

In [10]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.describe())

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
count,7916,7916,7916,7916
unique,13,54,5,4801
top,Back-End Developer JavaScript,Belajar Dasar Pemrograman JavaScript,Dasar,Forum Diskusi
freq,1022,620,2349,75

Learning Path

       learning_path_id
count          13.00000
mean            7.00000
std             3.89444
min             1.00000
25%             4.00000
50%             7.00000
75%            10.00000
max            13.00000

Course

       course_id  learning_path_id  course_level_str  hours_to_study
count  75.000000         75.000000         75.000000       75.000000
mean   38.000000          6.853333          2.400000       56.426667
std    21.794495          3.847405          1.196843       31.814994
min     1.000000          1.000000          1.000000       10.000000
25%    19.500000          3.500000          1.000000       35.000000
50%    38.000000          7.000000          2.000000       50.000000
75%    56.500000         10.000000          3.000000       80.000000
max    75.000000         13.000000          5.000000      150.000000

Course Level

             id
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

Tutorials

       tutorial_id    course_id
count  7771.000000  7771.000000
mean   3886.000000    36.854716
std    2243.438804    21.499002
min       1.000000     1.000000
25%    1943.500000    17.000000
50%    3886.000000    38.000000
75%    5828.500000    55.000000
max    7771.000000    75.000000

Learning Path Answer

               id
count   67.000000
mean   320.865672
std    178.280924
min     14.000000
25%    180.500000
50%    302.000000
75%    430.500000
max    663.000000

Current Interest Questions

,question_desc,option_text,category
count,20,20,20
unique,5,20,4
top,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
freq,4,1,5

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
count,326,326,326,326,326,326,326,326
unique,7,3,326,320,323,323,314,322
top,Web,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Linear Regression,Diagram lingkaran,Menarik garis dari view ke kode Swift,"Tidak ada perbedaan, keduanya adalah istilah y...",Semua jawaban benar
freq,52,148,1,2,2,2,4,4

Skill Keywords

                 id
count   5553.000000
mean   13609.798127
std     8007.380509
min        4.000000
25%     6681.000000
50%    13592.000000
75%    20837.000000
max    26318.000000

Student Progress

,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
count,271.000000,271.000000,271.000000,271.000000,132.000000,53.000000,254.000000,127.000000
mean,68.202952,51.428044,0.494465,0.594096,16795.454545,4.150943,23269.047244,87.897638
std,44.701472,61.022229,0.500894,5.856099,14108.154116,0.841158,12699.911633,16.735968
min,2.000000,0.000000,0.000000,0.000000,4.000000,2.000000,163.000000,2.000000
25%,38.000000,2.500000,0.000000,0.000000,4350.000000,4.000000,13827.000000,85.000000
50%,69.000000,39.000000,0.000000,0.000000,14967.000000,4.000000,24223.000000,92.000000
75%,107.000000,77.000000,1.000000,0.000000,29006.250000,5.000000,34451.750000,100.000000
max,189.000000,452.000000,1.000000,75.000000,40937.000000,5.000000,45722.000000,100.000000

In [11]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.info())

LP + Course
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7916 entries, 0 to 7915
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   learning_path_name  7916 non-null   object
 1   course_name         7916 non-null   object
 2   course_level_str    7916 non-null   object
 3   tutorial_title      7916 non-null   object
dtypes: object(4)
memory usage: 247.5+ KB

None

Learning Path
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   learning_path_id    13 non-null     int64
 1   learning_path_name  13 non-null     object
dtypes: int64(1), object(1)
memory usage: 340.0+ bytes

None

Course
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   course_id         75 non-null     int64
 1   learning_path_id  75 non-null     int64
 2   course_name       75 non-null     object
 3   course_level_str  75 non-null     int64
 4   hours_to_study    75 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.1+ KB

None

Course Level
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5 non-null      int64
 1   course_level  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

None

Tutorials
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7771 entries, 0 to 7770
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tutorial_id     7771 non-null   int64
 1   course_id       7771 non-null   int64
 2   tutorial_title  7771 non-null   object
 3   Unnamed: 3      319 non-null    object
 4   Unnamed: 4      167 non-null    object
dtypes: int64(2), object(3)
memory usage: 303.7+ KB

None

Learning Path Answer
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 67 non-null     int64
 1   name               67 non-null     object
 2   summary            67 non-null     object
 3   description        67 non-null     object
 4   course_difficulty  67 non-null     object
 5   course_price       67 non-null     object
 6   technologies       67 non-null     object
 7   course_type        67 non-null     object
 8   courseMeta         67 non-null     object
 9   courseInfo         67 non-null     object
dtypes: int64(1), object(9)
memory usage: 5.4+ KB

None

Current Interest Questions
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   question_desc  20 non-null     object
 1   option_text    20 non-null     object
 2   category       20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

None

Current Tech Questions
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tech_category   326 non-null    object
 1   difficulty      326 non-null    object
 2   question_desc   326 non-null    object
 3   option_1        326 non-null    object
 4   option_2        326 non-null    object
 5   option_3        326 non-null    object
 6   option_4        326 non-null    object
 7   correct_answer  326 non-null    object
dtypes: object(8)
memory usage: 20.5+ KB

None

Skill Keywords
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5553 entries, 0 to 5552
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       5553 non-null   int64
 1   keyword  5552 non-null   object
dtypes: int64(1), object(1)
memory usage: 86.9+ KB

None

Student Progress
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           271 non-null    object
 1   email                          271 non-null    object
 2   course_name                    271 non-null    object
 3   active_tutorials               271 non-null    int64
 4   completed_tutorials            271 non-null    int64
 5   is_graduated                   271 non-null    int64
 6   already_generated_certificate  271 non-null    int64
 7   final_submission_id            132 non-null    float64
 8   submission_rating              53 non-null     float64
 9   final_exam_id                  254 non-null    float64
 10  exam_score                     127 non-null    float64
dtypes: float64(4), int64(4), object(3)
memory usage: 23.4+ KB

None

## Prepocessing

In [12]:
# Cek Missing Value
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.isnull().sum())

LP + Course

learning_path_name    0
course_name           0
course_level_str      0
tutorial_title        0
dtype: int64

Learning Path

learning_path_id      0
learning_path_name    0
dtype: int64

Course

course_id           0
learning_path_id    0
course_name         0
course_level_str    0
hours_to_study      0
dtype: int64

Course Level

id              0
course_level    0
dtype: int64

Tutorials

tutorial_id          0
course_id            0
tutorial_title       0
Unnamed: 3        7452
Unnamed: 4        7604
dtype: int64

Learning Path Answer

id                   0
name                 0
summary              0
description          0
course_difficulty    0
course_price         0
technologies         0
course_type          0
courseMeta           0
courseInfo           0
dtype: int64

Current Interest Questions

question_desc    0
option_text      0
category         0
dtype: int64

Current Tech Questions

tech_category     0
difficulty        0
question_desc     0
option_1          0
option_2          0
option_3          0
option_4          0
correct_answer    0
dtype: int64

Skill Keywords

id         0
keyword    1
dtype: int64

Student Progress

name                               0
email                              0
course_name                        0
active_tutorials                   0
completed_tutorials                0
is_graduated                       0
already_generated_certificate      0
final_submission_id              139
submission_rating                218
final_exam_id                     17
exam_score                       144
dtype: int64

In [13]:
# Mengisi NaN dengan 0
skill_keywords.fillna(0, inplace=True)
stud_progress.fillna(0, inplace=True)

In [14]:
# Menghapus data duplikat LP + Course
lp_course = lp_course.drop_duplicates()
print("LP + Course duplicates removed:", lp_course.duplicated().sum())

LP + Course duplicates removed: 0

In [15]:
import pandas as pd
import re
import nltk
from tqdm import tqdm
tqdm.pandas()

In [16]:
def preprocess_text(text):
    if pd.isna(text):
        return ''
    text = str(text)

    return text

In [17]:
for name, df in datasets.items():
    print(f"\n{name}")
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].progress_apply(preprocess_text)

LP + Course

100%|██████████| 7916/7916 [00:00<00:00, 611941.51it/s]
100%|██████████| 7916/7916 [00:00<00:00, 772519.38it/s]
100%|██████████| 7916/7916 [00:00<00:00, 2282245.70it/s]
100%|██████████| 7916/7916 [00:00<00:00, 743658.26it/s]

Learning Path

100%|██████████| 13/13 [00:00<?, ?it/s]

Course

100%|██████████| 75/75 [00:00<00:00, 25413.86it/s]

Course Level

100%|██████████| 5/5 [00:00<?, ?it/s]

Tutorials

100%|██████████| 7771/7771 [00:00<00:00, 1122032.99it/s]
100%|██████████| 7771/7771 [00:00<00:00, 568879.25it/s]
100%|██████████| 7771/7771 [00:00<00:00, 848756.22it/s]

Learning Path Answer

100%|██████████| 67/67 [00:00<00:00, 56282.47it/s]
100%|██████████| 67/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<00:00, 33339.47it/s]
100%|██████████| 67/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<00:00, 18775.86it/s]
100%|██████████| 67/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<00:00, 181185.28it/s]
100%|██████████| 67/67 [00:00<?, ?it/s]
100%|██████████| 67/67 [00:00<?, ?it/s]

Current Interest Questions

100%|██████████| 20/20 [00:00<?, ?it/s]
100%|██████████| 20/20 [00:00<?, ?it/s]
100%|██████████| 20/20 [00:00<?, ?it/s]

Current Tech Questions

100%|██████████| 326/326 [00:00<?, ?it/s]
100%|██████████| 326/326 [00:00<00:00, 169519.35it/s]
100%|██████████| 326/326 [00:00<?, ?it/s]
100%|██████████| 326/326 [00:00<00:00, 110572.79it/s]
100%|██████████| 326/326 [00:00<00:00, 644061.75it/s]
100%|██████████| 326/326 [00:00<?, ?it/s]
100%|██████████| 326/326 [00:00<?, ?it/s]
100%|██████████| 326/326 [00:00<?, ?it/s]

Skill Keywords

100%|██████████| 5553/5553 [00:00<00:00, 773683.57it/s]

Student Progress

100%|██████████| 271/271 [00:00<00:00, 134213.77it/s]
100%|██████████| 271/271 [00:00<00:00, 151131.02it/s]
100%|██████████| 271/271 [00:00<?, ?it/s]

In [18]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
0,AI Engineer,Belajar Dasar AI,Dasar,Taksonomi AI
1,AI Engineer,Belajar Dasar AI,Dasar,[Story] Machine Learning: Harapan menjadi keny...
2,AI Engineer,Belajar Dasar AI,Dasar,Rangkuman Kelas
3,AI Engineer,Belajar Dasar AI,Dasar,Tipe-Tipe Machine Learning
4,AI Engineer,Belajar Dasar AI,Dasar,Forum Diskusi

Learning Path

   learning_path_id             learning_path_name
0                 1                    AI Engineer
1                 2              Android Developer
2                 3  Back-End Developer JavaScript
3                 4      Back-End Developer Python
4                 5                 Data Scientist

Course

,course_id,learning_path_id,course_name,course_level_str,hours_to_study
0,1,1,Belajar Dasar AI,1,10
1,2,1,Belajar Fundamental Deep Learning,3,110
2,3,1,Belajar Machine Learning untuk Pemula,2,90
3,4,1,Machine Learning Terapan,4,80
4,5,1,Membangun Proyek Deep Learning Tingkat Mahir,4,90

Course Level

   id course_level
0   1        Dasar
1   2       Pemula
2   3     Menengah
3   4        Mahir
4   5  Profesional

Tutorials

,tutorial_id,course_id,tutorial_title,Unnamed: 3,Unnamed: 4
0,1,1,Taksonomi AI,,
1,2,1,[Story] Machine Learning: Harapan menjadi keny...,,
2,3,1,Rangkuman Kelas,,
3,4,1,Tipe-Tipe Machine Learning,,
4,5,1,Forum Diskusi,,

Learning Path Answer

,id,name,summary,description,course_difficulty,course_price,technologies,course_type,courseMeta,courseInfo
0,14,Belajar Fundamental Aplikasi Android,Pelajari skill Android dengan kurikulum terlen...,Android merupakan sistem operasi mobile dengan...,Menengah,PAID,Android,Picodiploma,"['140 Jam', '4,84', 'Menengah']","['107 Modul', '41.831 Siswa Terdaftar']"
1,32,Belajar Membangun LINE Chatbot,Belajar membuat chatbot yang menarik pada plat...,LINE merupakan platform komunikasi yang sangat...,Pemula,PAID,"Android,Chatbot,Web",Reguler,"['20 Jam', '4,89', 'Pemula']","['26 Modul', '15.478 Siswa Terdaftar']"
2,51,Belajar Membuat Aplikasi Android untuk Pemula,Buat aplikasi pertamamu pada Android Studio de...,Android merupakan sistem operasi mobile dengan...,Pemula,PAID,Android,Reguler,"['60 Jam', '4,87', 'Pemula']","['49 Modul', '116.344 Siswa Terdaftar']"
3,60,Memulai Pemrograman Dengan Java,Belajar bahasa Java buat kamu yang ingin mempe...,Java merupakan bahasa yang diciptakan oleh Jam...,Dasar,FREE,"Android,Multi Platform",Reguler,"['15 Jam', '4,86', 'Dasar']","['42 Modul', '80.316 Siswa Terdaftar']"
4,80,Memulai Pemrograman dengan Kotlin,"Pelajari dasar bahasa pemrograman, functional ...",Kotlin merupakan bahasa utama yang digunakan d...,"Dasar,Pemula",PAID,"Android,Multi Platform",Reguler,"['50 Jam', '4,84', 'Dasar - Pemula']","['132 Modul', '59.512 Siswa Terdaftar']"

Current Interest Questions

,question_desc,option_text,category
0,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
1,Mana kegiatan yang paling relate denganmu di p...,Baca atau lihat info viral dari berbagai sumber,Artificial Intelligence
2,Mana kegiatan yang paling relate denganmu di p...,Membersihkan kamar,Cloud Computing
3,Mana kegiatan yang paling relate denganmu di p...,Coret-coret atau menulis di buku,Web Development
4,"Jika sedang menghadapi masalah, cara mana yang...",Coba berbagai cara sampai menemukan solusinya,Mobile Development

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
0,Android,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Komponen yang menangani tampilan pengguna,Kelas untuk menyimpan data,Fungsi untuk menjalankan proses di latar belakang,Antarmuka untuk menghubungkan database,Komponen yang menangani tampilan pengguna
1,Android,beginner,Apa fungsi utama dari file AndroidManifest.xml?,Menyimpan data aplikasi,Mendefinisikan struktur dan metadata aplikasi,Mengatur tata letak UI,Mengelola dependensi proyek,Mendefinisikan struktur dan metadata aplikasi
2,Android,beginner,"Dalam konteks Android, apa yang dimaksud denga...",Komponen untuk menyimpan data,Mekanisme untuk navigasi antar Activity,Fungsi untuk menangani error,Framework untuk membuat UI,Mekanisme untuk navigasi antar Activity
3,Android,beginner,Apa perbedaan utama antara LinearLayout dan Re...,"LinearLayout hanya untuk orientasi vertikal, R...","LinearLayout mengatur elemen secara berurutan,...","LinearLayout untuk aplikasi sederhana, Relativ...","Tidak ada perbedaan, keduanya dapat digunakan ...","LinearLayout mengatur elemen secara berurutan,..."
4,Android,beginner,Apa fungsi dari metode onCreate() dalam sebuah...,Menghapus Activity,Menginisialisasi Activity dan memuat layout,Menjalankan proses di background,Mengatur animasi transisi,Menginisialisasi Activity dan memuat layout

Skill Keywords

   id     keyword
0   4  JavaScript
1   9        Java
2  14      Python
3  19      Kotlin
4  24         PHP

Student Progress

,name,email,course_name,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
0,Dina Wijaya,dina.wijaya1@example.com,Belajar Membangun Aplikasi Android Native Bagi...,4,0,0,0,4.0,0.0,0.0,0.0
1,Irfan Halim,irfan.halim2@example.com,Belajar Membangun Aplikasi dengan Universal Wi...,10,0,0,0,76.0,0.0,0.0,0.0
2,Hana Pratama,hana.pratama3@example.com,Belajar Fundamental Aplikasi Android,107,1,0,0,1099.0,0.0,163.0,0.0
3,Dina Utama,dina.utama4@example.com,Belajar Fundamental Aplikasi Android,107,0,0,0,1099.0,0.0,163.0,0.0
4,Rafi Santoso,rafi.santoso5@example.com,Belajar Fundamental Aplikasi Android,107,55,0,0,1099.0,0.0,163.0,0.0

1. Rekomendasi roadmap minimal 1 job role dengan 6 sub-skill

In [19]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (2.28.1)
Requirement already satisfied: google-api-python-client in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (2.187.0)
Requirement already satisfied: google-auth>=2.15.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (2.43.0)
Requirement already satisfied: protobuf in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (2.9.2)
Requirement already satisfied: tqdm in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-core->google-generativeai) (2.32.5)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (6.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.11.12)
Requirement already satisfied: pyasn1>=0.1.3 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-python-client->google-generativeai) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-python-client->google-generativeai) (0.2.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.0.4 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from pydantic->google-generativeai) (2.23.4)
Requirement already satisfied: colorama in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from tqdm->google-generativeai) (0.4.6)

In [20]:
pip install sentence-transformers scikit-learn

Requirement already satisfied: sentence-transformers in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (5.1.2)
Requirement already satisfied: scikit-learn in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (1.7.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (4.57.1)
Requirement already satisfied: tqdm in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (2.9.1)
Requirement already satisfied: scipy in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (12.0.0)
Requirement already satisfied: typing_extensions>=4.5.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.20.0)
Requirement already satisfied: numpy>=1.17 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.3.4)
Requirement already satisfied: packaging>=20.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: requests in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.10.0)
Requirement already satisfied: joblib>=1.2.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: sympy>=1.13.3 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6)
Requirement already satisfied: jinja2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\asah by dicoding\dc - 06 learning budy\dicoding-asah-learning-buddy\backend\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [21]:
# Clean skill keywords
stopwords = {
    "dan","saya","yang","dengan","ke","di","pada","untuk",
    "adalah","ini","basic","advanced","intro","beginner",
    "dasar","program","programming","pemrograman","bahasa",
    "membuat","make","using","menggunakan", "engineer", "juggling", "jarngan"
}

def clean_text(text):
    text = re.sub(r'[^\w\s/]', ' ', text)
    words = [w for w in text.split() if w.lower() not in stopwords]
    return " ".join(words)

skill_keywords['keyword'] = skill_keywords['keyword'].fillna("").apply(clean_text)

In [22]:
import re
import random
import torch
from sentence_transformers import SentenceTransformer, util
import google.generativeai as genai
import pandas as pd
from difflib import get_close_matches

# Setup Gemini API
genai.configure(api_key="AIzaSyCXZFUY0CAy3l_xJRTxfaXUFBeSpLWNz-I")
model = genai.GenerativeModel("models/gemini-2.5-flash")

# Load Embedding Model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Detect Job Role
job_role = learning_path['learning_path_name'].dropna().unique().tolist()

def detect_job_role(user_input, job_role):
    prompt = f"""
    Anda adalah asisten pintar yang bertugas untuk mengklasifikasikan deskripsi pengguna ke job role yang paling tepat.

    Petunjuk:
    1. Analisis deskripsi pengguna secara menyeluruh.
    2. Bandingkan dengan daftar job role berikut, pilih yang paling relevan.
    3. Hanya pilih **satu job role** yang paling cocok.
    4. Jawaban **hanya berupa nama job role**, tanpa penjelasan, tanda kutip, atau teks tambahan.
    5. Jika tidak yakin, pilih job role yang paling mendekati, jangan buat job role baru.

    Job role valid:
    {job_role}

    Deskripsi pengguna:
    "{user_input}"
    """
    response = model.generate_content(prompt)
    return response.text.strip() if response.text else "Unknown"

# Detect Subskills
def detect_subskills(user_input, job_role, top_k=6):
    prompt = f"""
    Anda adalah AI pakar dalam technical skill assessment untuk berbagai job role IT.

    ATURAN SUPER KETAT:
    1. Hanya ambil subskill dari dataset berikut: {skill_keywords}.
    2. Subskill harus sesuai job role (bahasa pemrograman, library, framework, DevOps/MLOps tools)
    3. DILARANG: subskill generik, teori, platform software/cloud, metodologi, tools non-teknis/desain, version control, platform dan library yang tidak relevan dengan job role.
    4. Output HARUS EXACT {top_k} subskill, pisah koma, tanpa penjelasan.
    Job Role: {job_role}
    User Input: {user_input}

    Output:
    """

    try:
        resp = model.generate_content(prompt)
        raw_items = [s.strip() for s in resp.text.replace("\n", "").split(",") if s.strip()]
    except Exception as e:
        print("LLM gagal:", e)
        raw_items = []

    # Ambil subskill yang valid dari dataset saja
    valid_keywords = skill_keywords['keyword'].dropna().tolist()
    filtered = []

    for item in raw_items:
        match = get_close_matches(item, valid_keywords, n=1, cutoff=0.6)
        if match and match[0] not in filtered:
            filtered.append(match[0])

    # Jika kurang dari top_k, isi dengan subskill lain dari dataset
    if len(filtered) < top_k:
        remaining = [k for k in valid_keywords if k not in filtered]
        filtered.extend(remaining[:top_k - len(filtered)])

    return filtered[:top_k]


# Ambil pertanyaan dari dataset tech_qs
from difflib import SequenceMatcher
import pandas as pd

def get_questions_for_subskill_from_dataset(subskill, tech_qs, num_questions=3):
    filtered = tech_qs[tech_qs['question_desc'].str.contains(subskill, case=False, na=False)]

    if len(filtered) >= num_questions:
        filtered = filtered.sample(n=num_questions)
    elif len(filtered) == 0:
        return None

    questions = []
    for _, row in filtered.iterrows():
        # Ambil semua opsi
        options = [
            str(row['option_1']).strip(),
            str(row['option_2']).strip(),
            str(row['option_3']).strip(),
            str(row['option_4']).strip()
        ]

        # Format opsi dengan huruf (A. B. C. D.)
        formatted_options = [f"{chr(65+i)}. {opt}" for i, opt in enumerate(options)]

        # Convert correct_answer (text) ke huruf (A/B/C/D)
        if pd.isna(row['correct_answer']):
            answer_letter = None  # Tandai tidak ada jawaban
        else:
            correct_text = str(row['correct_answer']).strip()
            answer_letter = None  # Default

            # Cari exact match dulu (case-insensitive)
            for i, opt in enumerate(options):
                if opt.lower() == correct_text.lower():
                    answer_letter = chr(65 + i)  # 0→A, 1→B, 2→C, 3→D
                    break

            # Jika tidak ketemu, coba fuzzy matching
            if answer_letter is None:
                best_match_idx = 0
                best_similarity = 0

                for i, opt in enumerate(options):
                    similarity = SequenceMatcher(None, opt.lower(), correct_text.lower()).ratio()
                    if similarity > best_similarity:
                        best_similarity = similarity
                        best_match_idx = i

                # Jika similarity > 80%, anggap match
                if best_similarity > 0.8:
                    answer_letter = chr(65 + best_match_idx)
                else:
                    print(f"Warning: Jawaban '{correct_text[:40]}...' tidak ditemukan!")
                    answer_letter = None

        questions.append({
            "question": row['question_desc'],
            "options": formatted_options,
            "answer": answer_letter  # "A"/"B"/"C"/"D" atau None
        })

    return questions


# Generate pertanyaan via Gemini
def generate_questions_gemini(subskill, num_questions=3):
    prompt = f"""
    Anda adalah AI pakar pembuat pertanyaan teknologi.

    Buat {num_questions} pertanyaan pilihan ganda terkait subskill: "{subskill}".
    Setiap pertanyaan harus memiliki 4 opsi jawaban (A, B, C, D), **tanpa menuliskan jawaban benar**.
    Output cukup dalam text biasa, misal:

    1. Pertanyaan?
    A. jawaban1
    B. jawaban2
    C. jawaban3
    D. jawaban4
    """
    try:
        resp = model.generate_content(prompt)
        resp_text = resp.text.strip()

        questions = []
        q = {}
        lines = resp_text.split("\n")
        answer_index_cycle = list(range(4))

        for line in lines:
            line = line.strip()
            if re.match(r"^\d+\.", line):
                question_text = re.sub(r"^\d+\.\s*", "", line).strip()
                if q:
                    if q.get("options"):
                        answer_idx = answer_index_cycle.pop(0)
                        answer_index_cycle.append(answer_idx)
                        q["answer"] = q["options"][answer_idx][0]
                    else:
                        q["answer"] = "A"
                    questions.append(q)
                q = {"question": question_text, "options": [], "answer": "A"}
            elif re.match(r"^[A-D]\.", line):
                q.setdefault("options", []).append(line)
        if q:
            if q.get("options"):
                answer_idx = answer_index_cycle.pop(0)
                answer_index_cycle.append(answer_idx)
                q["answer"] = q["options"][answer_idx][0]
            else:
                q["answer"] = "A"
            questions.append(q)

        return questions[:num_questions]

    except Exception as e:
        print("LLM gagal membuat pertanyaan:", e)
        return []

# Prepare assessment
def prepare_assessment(detected_subskills, tech_qs, total_questions=18):
    num_subskills = len(detected_subskills)
    questions_per_subskill = total_questions // num_subskills

    assessment = {}
    for subskill in detected_subskills:
        questions = get_questions_for_subskill_from_dataset(subskill, tech_qs, num_questions=questions_per_subskill)
        if questions is None or len(questions) < questions_per_subskill:
            needed = questions_per_subskill if questions is None else questions_per_subskill - len(questions)
            generated = generate_questions_gemini(subskill, num_questions=needed)
            questions = (questions or []) + generated

        for i, q in enumerate(questions):
            q.setdefault("question", "Pertanyaan tidak tersedia")
            q.setdefault("options", ["A. ...", "B. ...", "C. ...", "D. ..."])
            q.setdefault("answer", "A")

        assessment[subskill] = questions

    return assessment

# Run assessment
def run_assessment(assessment):
    results = {}

    for subskill, questions in assessment.items():
        print(f"\nSubskill: {subskill}")
        correct_count = 0
        for idx, q in enumerate(questions, 1):
            print(f"\n{idx}. {q['question']}")

            options = q.get('options', ["A. ...", "B. ...", "C. ...", "D. ..."])
            for opt in options:
                print(opt)

            user_answer = input("Jawaban (A/B/C/D): ").strip().upper()
            while user_answer not in ['A','B','C','D']:
                user_answer = input("Jawaban salah. Masukkan A/B/C/D: ").strip().upper()

            if user_answer == q.get('answer','A').upper():
                correct_count += 1

        if correct_count == len(questions):
            level = "Advanced"
        elif correct_count >= len(questions) - 1:
            level = "Intermediate"
        else:
            level = "Beginner"

        results[subskill] = {
            "correct": correct_count,
            "total": len(questions),
            "level": level
        }

    return results

# Hasil
user_input = input("Masukkan deskripsi user: ")

job_role_detected = detect_job_role(user_input, job_role)
subskills_detected = detect_subskills(user_input, job_role_detected, top_k=6)

print("Job Role:", job_role_detected)
print("Subskill:", ", ".join(subskills_detected))

total_q = int(input("Pilih total pertanyaan (18 atau 36): "))

assessment = prepare_assessment(subskills_detected, tech_qs, total_questions=total_q)
results = run_assessment(assessment)

print("\nHasil Assessment")
for subskill, res in results.items():
    print(f"{subskill}: {res['correct']}/{res['total']} benar, Level: {res['level']}")

d:\Asah by Dicoding\DC - 06 Learning budy\dicoding-asah-learning-buddy\backend\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Job Role: AI Engineer
Subskill: Python, TensorFlow, PyTorch, scikit learn, Pandas, Docker

Subskill: Python

1. Apa output dari ekspresi Python berikut: 3 * 2 ** 3?
A. 18
B. 24
C. 9
D. 36

2. Dalam Python, bagaimana cara mendeklarasikan variabel?
A. var x = 5
B. let x = 5
C. x = 5
D. int x = 5

3. Manakah dari berikut ini yang merupakan tipe data sekuensial dalam Python?
A. Integer
B. Float
C. List
D. Boolean

Subskill: TensorFlow

1. Apa keuntungan utama dari menggunakan TensorFlow.js untuk deploy model machine learning?
A. Meningkatkan akurasi model
B. Memungkinkan inferensi model di browser atau Node.js
C. Mempercepat proses training model
D. Mengurangi ukuran dataset yang diperlukan

2. Manakah dari API berikut yang menjadi antarmuka tingkat tinggi utama untuk membangun dan melatih model pembelajaran mendalam dalam TensorFlow 2.x?
A. `tf.Estimator`
B. `tf.data`
C. `tf.keras`
D. `tf.io`

3. Dalam konteks TensorFlow, apa struktur data fundamental yang digunakan untuk merepresentasikan data (seperti input, bobot, dan output) dalam semua operasi dan komputasi?
A. NumPy array
B. Python list
C. Tensor
D. DataFrame

Subskill: PyTorch

1. Apa kegunaan utama dari metode `backward()` pada PyTorch tensor?
A. Untuk memindahkan tensor ke perangkat GPU.
B. Untuk menghitung gradien dari suatu fungsi berdasarkan tensor tersebut.
C. Untuk mengubah bentuk (reshape) tensor menjadi dimensi yang berbeda.
D. Untuk melakukan operasi perkalian matriks secara terbalik.

2. Dalam PyTorch, komponen mana yang bertanggung jawab untuk mengelola parameter yang dapat dilatih (trainable parameters) dan menyediakan fungsionalitas lapisan jaringan saraf?
A. `torch.Tensor`
B. `torch.optim`
C. `torch.nn.Module`
D. `torch.utils.data.DataLoader`

3. Opsi mana yang paling tepat untuk memindahkan PyTorch tensor bernama `x` ke perangkat GPU (jika tersedia)?
A. `x.cpu().to('cuda')`
B. `x.to('gpu')`
C. `x.cuda()`
D. `torch.device(x, 'cuda')`

Subskill: scikit learn

1. Metode mana yang digunakan pada objek estimator Scikit-learn untuk melatih model menggunakan data pelatihan?
A. `predict()`
B. `transform()`
C. `fit()`
D. `score()`

2. Untuk melakukan penskalaan fitur (feature scaling) seperti standardisasi atau normalisasi pada dataset, modul Scikit-learn mana yang paling sering digunakan?
A. `sklearn.model_selection`
B. `sklearn.metrics`
C. `sklearn.preprocessing`
D. `sklearn.decomposition`

3. Dalam Scikit-learn, teknik apa yang digunakan untuk menggabungkan beberapa langkah pemrosesan data dan estimasi model menjadi satu objek tunggal, membantu mencegah kebocoran data (data leakage) dan menyederhanakan kode?
A. `cross_val_score`
B. `GridSearchCV`
C. `Pipeline`
D. `make_scorer`

Subskill: Pandas

1. Dalam Pandas, struktur data mana yang paling sering digunakan untuk merepresentasikan data tabular dengan kolom berlabel dan baris berindeks, mirip dengan spreadsheet atau tabel database?
A. Series
B. Array
C. DataFrame
D. List

2. Jika Anda memiliki DataFrame bernama `df` dan ingin memilih kolom tunggal bernama 'Produk', sintaksis mana yang paling tepat dan umum digunakan di Pandas?
A. `df.select_column('Produk')`
B. `df['Produk']`
C. `df.column('Produk')`
D. `df.get_column('Produk')`

3. Untuk menghapus baris dari DataFrame `df` yang mengandung setidaknya satu nilai yang hilang (NaN), metode Pandas mana yang paling sesuai?
A. `df.drop_na()`
B. `df.remove_nan()`
C. `df.dropna()`
D. `df.fill_na(0)`

Subskill: Docker

1. Apa tujuan utama dari Dockerfile?
A. Untuk mendefinisikan konfigurasi jaringan antar kontainer.
B. Untuk memberikan instruksi langkah demi langkah dalam membangun Docker image.
C. Untuk menjalankan perintah di dalam kontainer yang sudah berjalan.
D. Untuk mempublikasikan image ke Docker Hub.

2. Perintah Docker manakah yang digunakan untuk menjalankan image sebagai sebuah kontainer baru?
A. `docker build`
B. `docker pull`
C. `docker run`
D. `docker commit`

3. Dalam konteks Docker, apa manfaat utama dari menggunakan "volume"?
A. Untuk membatasi akses CPU dan memori yang digunakan oleh kontainer.
B. Untuk memastikan data dalam kontainer tetap ada (persistent) meskipun kontainer dihapus atau dibuat ulang.
C. Untuk mengelola siklus hidup Docker daemon.
D. Untuk mengoptimalkan transfer file antar host dan kontainer secara real-time.

Hasil Assessment
Python: 1/3 benar, Level: Beginner
TensorFlow: 2/3 benar, Level: Intermediate
PyTorch: 1/3 benar, Level: Beginner
scikit learn: 1/3 benar, Level: Beginner
Pandas: 1/3 benar, Level: Beginner
Docker: 1/3 benar, Level: Beginner