## Import Library

In [ ]:
import pandas as pd

## Load Dataset

In [ ]:
lp_mapping = pd.read_excel('LP and Course Mapping.xlsx', sheet_name=None)
resource_data = pd.read_excel('Resource Data Learning Buddy.xlsx', sheet_name=None)

datasets = {}
datasets.update(lp_mapping)
datasets.update(resource_data)

print("LP and Course Mapping:", lp_mapping.keys())
print("Resource Data Learning Buddy:", resource_data.keys())

LP and Course Mapping: dict_keys(['LP + Course', 'Learning Path', 'Course', 'Course Level', 'Tutorials'])
Resource Data Learning Buddy: dict_keys(['Learning Path Answer', 'Current Interest Questions', 'Current Tech Questions', 'Skill Keywords', 'Student Progress'])

In [ ]:
# Pisahkan sheet ke variabel masing-masing
# LP and Course Mapping
lp_course = lp_mapping['LP + Course']
learning_path = lp_mapping['Learning Path']
course = lp_mapping['Course']
course_level = lp_mapping['Course Level']
tutorials = lp_mapping['Tutorials']

# Resource Data Learning Buddy
lp_answer = resource_data['Learning Path Answer']
interest_qs = resource_data['Current Interest Questions']
tech_qs = resource_data['Current Tech Questions']
skill_keywords = resource_data['Skill Keywords']
stud_progress = resource_data['Student Progress']

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())
    print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
0,AI Engineer,Belajar Dasar AI,Dasar,Taksonomi AI
1,AI Engineer,Belajar Dasar AI,Dasar,[Story] Machine Learning: Harapan menjadi keny...
2,AI Engineer,Belajar Dasar AI,Dasar,Rangkuman Kelas
3,AI Engineer,Belajar Dasar AI,Dasar,Tipe-Tipe Machine Learning
4,AI Engineer,Belajar Dasar AI,Dasar,Forum Diskusi

Shape: 7916 rows × 4 columns

Learning Path

   learning_path_id             learning_path_name
0                 1                    AI Engineer
1                 2              Android Developer
2                 3  Back-End Developer JavaScript
3                 4      Back-End Developer Python
4                 5                 Data Scientist

Shape: 13 rows × 2 columns

Course

,course_id,learning_path_id,course_name,course_level_str,hours_to_study
0,1,1,Belajar Dasar AI,1,10
1,2,1,Belajar Fundamental Deep Learning,3,110
2,3,1,Belajar Machine Learning untuk Pemula,2,90
3,4,1,Machine Learning Terapan,4,80
4,5,1,Membangun Proyek Deep Learning Tingkat Mahir,4,90

Shape: 75 rows × 5 columns

Course Level

   id course_level
0   1        Dasar
1   2       Pemula
2   3     Menengah
3   4        Mahir
4   5  Profesional

Shape: 5 rows × 2 columns

Tutorials

   tutorial_id  course_id                                     tutorial_title
0            1          1                                       Taksonomi AI
1            2          1  [Story] Machine Learning: Harapan menjadi keny...
2            3          1                                    Rangkuman Kelas
3            4          1                         Tipe-Tipe Machine Learning
4            5          1                                      Forum Diskusi

Shape: 7771 rows × 3 columns

Learning Path Answer

,id,name,summary,description,course_difficulty,course_price,technologies,course_type,courseMeta,courseInfo
0,14,Belajar Fundamental Aplikasi Android,Pelajari skill Android dengan kurikulum terlen...,Android merupakan sistem operasi mobile dengan...,Menengah,PAID,Android,Picodiploma,"['140 Jam', '4,84', 'Menengah']","['107 Modul', '41.831 Siswa Terdaftar']"
1,32,Belajar Membangun LINE Chatbot,Belajar membuat chatbot yang menarik pada plat...,LINE merupakan platform komunikasi yang sangat...,Pemula,PAID,"Android,Chatbot,Web",Reguler,"['20 Jam', '4,89', 'Pemula']","['26 Modul', '15.478 Siswa Terdaftar']"
2,51,Belajar Membuat Aplikasi Android untuk Pemula,Buat aplikasi pertamamu pada Android Studio de...,Android merupakan sistem operasi mobile dengan...,Pemula,PAID,Android,Reguler,"['60 Jam', '4,87', 'Pemula']","['49 Modul', '116.344 Siswa Terdaftar']"
3,60,Memulai Pemrograman Dengan Java,Belajar bahasa Java buat kamu yang ingin mempe...,Java merupakan bahasa yang diciptakan oleh Jam...,Dasar,FREE,"Android,Multi Platform",Reguler,"['15 Jam', '4,86', 'Dasar']","['42 Modul', '80.316 Siswa Terdaftar']"
4,80,Memulai Pemrograman dengan Kotlin,"Pelajari dasar bahasa pemrograman, functional ...",Kotlin merupakan bahasa utama yang digunakan d...,"Dasar,Pemula",PAID,"Android,Multi Platform",Reguler,"['50 Jam', '4,84', 'Dasar - Pemula']","['132 Modul', '59.512 Siswa Terdaftar']"

Shape: 67 rows × 10 columns

Current Interest Questions

,question_desc,option_text,category
0,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
1,Mana kegiatan yang paling relate denganmu di p...,Baca atau lihat info viral dari berbagai sumber,Artificial Intelligence
2,Mana kegiatan yang paling relate denganmu di p...,Membersihkan kamar,Cloud Computing
3,Mana kegiatan yang paling relate denganmu di p...,Coret-coret atau menulis di buku,Web Development
4,"Jika sedang menghadapi masalah, cara mana yang...",Coba berbagai cara sampai menemukan solusinya,Mobile Development

Shape: 20 rows × 3 columns

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
0,Android,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Komponen yang menangani tampilan pengguna,Kelas untuk menyimpan data,Fungsi untuk menjalankan proses di latar belakang,Antarmuka untuk menghubungkan database,Komponen yang menangani tampilan pengguna
1,Android,beginner,Apa fungsi utama dari file AndroidManifest.xml?,Menyimpan data aplikasi,Mendefinisikan struktur dan metadata aplikasi,Mengatur tata letak UI,Mengelola dependensi proyek,Mendefinisikan struktur dan metadata aplikasi
2,Android,beginner,"Dalam konteks Android, apa yang dimaksud denga...",Komponen untuk menyimpan data,Mekanisme untuk navigasi antar Activity,Fungsi untuk menangani error,Framework untuk membuat UI,Mekanisme untuk navigasi antar Activity
3,Android,beginner,Apa perbedaan utama antara LinearLayout dan Re...,"LinearLayout hanya untuk orientasi vertikal, R...","LinearLayout mengatur elemen secara berurutan,...","LinearLayout untuk aplikasi sederhana, Relativ...","Tidak ada perbedaan, keduanya dapat digunakan ...","LinearLayout mengatur elemen secara berurutan,..."
4,Android,beginner,Apa fungsi dari metode onCreate() dalam sebuah...,Menghapus Activity,Menginisialisasi Activity dan memuat layout,Menjalankan proses di background,Mengatur animasi transisi,Menginisialisasi Activity dan memuat layout

Shape: 326 rows × 8 columns

Skill Keywords

   id     keyword
0   4  JavaScript
1   9        Java
2  14      Python
3  19      Kotlin
4  24         PHP

Shape: 5553 rows × 2 columns

Student Progress

,name,email,password,course_name,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
0,Dina Wijaya,dina.wijaya1@example.com,admin,Belajar Membangun Aplikasi Android Native Bagi...,4,0,0,0,4.0,NaN,NaN,NaN
1,Irfan Halim,irfan.halim2@example.com,admin,Belajar Membangun Aplikasi dengan Universal Wi...,10,0,0,0,76.0,NaN,NaN,NaN
2,Hana Pratama,hana.pratama3@example.com,admin,Belajar Fundamental Aplikasi Android,107,1,0,0,1099.0,NaN,163.0,NaN
3,Dina Utama,dina.utama4@example.com,admin,Belajar Fundamental Aplikasi Android,107,0,0,0,1099.0,NaN,163.0,NaN
4,Rafi Santoso,rafi.santoso5@example.com,admin,Belajar Fundamental Aplikasi Android,107,55,0,0,1099.0,NaN,163.0,NaN

Shape: 271 rows × 12 columns

In [ ]:
# Dictionary untuk looping
datasets = {
    "LP + Course": lp_course,
    "Learning Path": learning_path,
    "Course": course,
    "Course Level": course_level,
    "Tutorials": tutorials,
    "Learning Path Answer": lp_answer,
    "Current Interest Questions": interest_qs,
    "Current Tech Questions": tech_qs,
    "Skill Keywords": skill_keywords,
    "Student Progress": stud_progress
}

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.describe())

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
count,7916,7916,7916,7916
unique,13,54,5,4801
top,Back-End Developer JavaScript,Belajar Dasar Pemrograman JavaScript,Dasar,Forum Diskusi
freq,1022,620,2349,75

Learning Path

       learning_path_id
count          13.00000
mean            7.00000
std             3.89444
min             1.00000
25%             4.00000
50%             7.00000
75%            10.00000
max            13.00000

Course

       course_id  learning_path_id  course_level_str  hours_to_study
count  75.000000         75.000000         75.000000       75.000000
mean   38.000000          6.853333          2.400000       56.426667
std    21.794495          3.847405          1.196843       31.814994
min     1.000000          1.000000          1.000000       10.000000
25%    19.500000          3.500000          1.000000       35.000000
50%    38.000000          7.000000          2.000000       50.000000
75%    56.500000         10.000000          3.000000       80.000000
max    75.000000         13.000000          5.000000      150.000000

Course Level

             id
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

Tutorials

       tutorial_id    course_id
count  7771.000000  7771.000000
mean   3886.000000    36.854716
std    2243.438804    21.499002
min       1.000000     1.000000
25%    1943.500000    17.000000
50%    3886.000000    38.000000
75%    5828.500000    55.000000
max    7771.000000    75.000000

Learning Path Answer

               id
count   67.000000
mean   320.865672
std    178.280924
min     14.000000
25%    180.500000
50%    302.000000
75%    430.500000
max    663.000000

Current Interest Questions

,question_desc,option_text,category
count,20,20,20
unique,5,20,4
top,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
freq,4,1,5

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
count,326,326,326,326,326,326,326,326
unique,7,3,326,320,323,323,314,322
top,Web,beginner,Apa fungsi utama dari service worker dalam web...,Linear Regression,Untuk membuat antarmuka pengguna,Menarik garis dari view ke kode Swift,"Tidak ada perbedaan, keduanya adalah istilah y...",Semua jawaban benar
freq,52,148,1,2,2,2,4,4

Skill Keywords

                 id
count   5553.000000
mean   13609.798127
std     8007.380509
min        4.000000
25%     6681.000000
50%    13592.000000
75%    20837.000000
max    26318.000000

Student Progress

,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
count,271.000000,271.000000,271.000000,271.000000,132.000000,53.000000,254.000000,127.000000
mean,68.202952,51.428044,0.494465,0.594096,16795.454545,4.150943,23269.047244,87.897638
std,44.701472,61.022229,0.500894,5.856099,14108.154116,0.841158,12699.911633,16.735968
min,2.000000,0.000000,0.000000,0.000000,4.000000,2.000000,163.000000,2.000000
25%,38.000000,2.500000,0.000000,0.000000,4350.000000,4.000000,13827.000000,85.000000
50%,69.000000,39.000000,0.000000,0.000000,14967.000000,4.000000,24223.000000,92.000000
75%,107.000000,77.000000,1.000000,0.000000,29006.250000,5.000000,34451.750000,100.000000
max,189.000000,452.000000,1.000000,75.000000,40937.000000,5.000000,45722.000000,100.000000

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.info())

LP + Course
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7916 entries, 0 to 7915
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   learning_path_name  7916 non-null   object
 1   course_name         7916 non-null   object
 2   course_level_str    7916 non-null   object
 3   tutorial_title      7916 non-null   object
dtypes: object(4)
memory usage: 247.5+ KB

None

Learning Path
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   learning_path_id    13 non-null     int64
 1   learning_path_name  13 non-null     object
dtypes: int64(1), object(1)
memory usage: 340.0+ bytes

None

Course
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   course_id         75 non-null     int64
 1   learning_path_id  75 non-null     int64
 2   course_name       75 non-null     object
 3   course_level_str  75 non-null     int64
 4   hours_to_study    75 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.1+ KB

None

Course Level
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5 non-null      int64
 1   course_level  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

None

Tutorials
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7771 entries, 0 to 7770
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tutorial_id     7771 non-null   int64
 1   course_id       7771 non-null   int64
 2   tutorial_title  7771 non-null   object
dtypes: int64(2), object(1)
memory usage: 182.3+ KB

None

Learning Path Answer
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 67 non-null     int64
 1   name               67 non-null     object
 2   summary            67 non-null     object
 3   description        67 non-null     object
 4   course_difficulty  67 non-null     object
 5   course_price       67 non-null     object
 6   technologies       67 non-null     object
 7   course_type        67 non-null     object
 8   courseMeta         67 non-null     object
 9   courseInfo         67 non-null     object
dtypes: int64(1), object(9)
memory usage: 5.4+ KB

None

Current Interest Questions
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   question_desc  20 non-null     object
 1   option_text    20 non-null     object
 2   category       20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

None

Current Tech Questions
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tech_category   326 non-null    object
 1   difficulty      326 non-null    object
 2   question_desc   326 non-null    object
 3   option_1        326 non-null    object
 4   option_2        326 non-null    object
 5   option_3        326 non-null    object
 6   option_4        326 non-null    object
 7   correct_answer  326 non-null    object
dtypes: object(8)
memory usage: 20.5+ KB

None

Skill Keywords
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5553 entries, 0 to 5552
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       5553 non-null   int64
 1   keyword  5552 non-null   object
dtypes: int64(1), object(1)
memory usage: 86.9+ KB

None

Student Progress
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           271 non-null    object
 1   email                          271 non-null    object
 2   password                       271 non-null    object
 3   course_name                    271 non-null    object
 4   active_tutorials               271 non-null    int64
 5   completed_tutorials            271 non-null    int64
 6   is_graduated                   271 non-null    int64
 7   already_generated_certificate  271 non-null    int64
 8   final_submission_id            132 non-null    float64
 9   submission_rating              53 non-null     float64
 10  final_exam_id                  254 non-null    float64
 11  exam_score                     127 non-null    float64
dtypes: float64(4), int64(4), object(4)
memory usage: 25.5+ KB

None

## Prepocessing

In [ ]:
# Cek Missing Value
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.isnull().sum())

LP + Course

learning_path_name    0
course_name           0
course_level_str      0
tutorial_title        0
dtype: int64

Learning Path

learning_path_id      0
learning_path_name    0
dtype: int64

Course

course_id           0
learning_path_id    0
course_name         0
course_level_str    0
hours_to_study      0
dtype: int64

Course Level

id              0
course_level    0
dtype: int64

Tutorials

tutorial_id       0
course_id         0
tutorial_title    0
dtype: int64

Learning Path Answer

id                   0
name                 0
summary              0
description          0
course_difficulty    0
course_price         0
technologies         0
course_type          0
courseMeta           0
courseInfo           0
dtype: int64

Current Interest Questions

question_desc    0
option_text      0
category         0
dtype: int64

Current Tech Questions

tech_category     0
difficulty        0
question_desc     0
option_1          0
option_2          0
option_3          0
option_4          0
correct_answer    0
dtype: int64

Skill Keywords

id         0
keyword    1
dtype: int64

Student Progress

name                               0
email                              0
password                           0
course_name                        0
active_tutorials                   0
completed_tutorials                0
is_graduated                       0
already_generated_certificate      0
final_submission_id              139
submission_rating                218
final_exam_id                     17
exam_score                       144
dtype: int64

In [ ]:
# Mengisi NaN dengan 0
skill_keywords.fillna(0, inplace=True)
stud_progress.fillna(0, inplace=True)

In [ ]:
# Menghapus data duplikat LP + Course
lp_course = lp_course.drop_duplicates()
print("LP + Course duplicates removed:", lp_course.duplicated().sum())

LP + Course duplicates removed: 0

In [ ]:
import pandas as pd
import re
import nltk
from tqdm import tqdm
tqdm.pandas()

In [ ]:
def preprocess_text(text):
    if pd.isna(text):
        return ''
    text = str(text)

    return text

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].progress_apply(preprocess_text)

LP + Course

100%|██████████| 7916/7916 [00:00<00:00, 1065981.01it/s]
100%|██████████| 7916/7916 [00:00<00:00, 1188421.16it/s]
100%|██████████| 7916/7916 [00:00<00:00, 1112298.51it/s]
100%|██████████| 7916/7916 [00:00<00:00, 779373.97it/s]

Learning Path

100%|██████████| 13/13 [00:00<00:00, 53300.05it/s]

Course

100%|██████████| 75/75 [00:00<00:00, 277891.17it/s]

Course Level

100%|██████████| 5/5 [00:00<00:00, 21312.52it/s]

Tutorials

100%|██████████| 7771/7771 [00:00<00:00, 878400.70it/s]

Learning Path Answer

100%|██████████| 67/67 [00:00<00:00, 197205.87it/s]
100%|██████████| 67/67 [00:00<00:00, 184880.51it/s]
100%|██████████| 67/67 [00:00<00:00, 194880.98it/s]
100%|██████████| 67/67 [00:00<00:00, 191559.90it/s]
100%|██████████| 67/67 [00:00<00:00, 198319.24it/s]
100%|██████████| 67/67 [00:00<00:00, 194745.92it/s]
100%|██████████| 67/67 [00:00<00:00, 152561.55it/s]
100%|██████████| 67/67 [00:00<00:00, 210343.09it/s]
100%|██████████| 67/67 [00:00<00:00, 101085.74it/s]

Current Interest Questions

100%|██████████| 20/20 [00:00<00:00, 75234.15it/s]
100%|██████████| 20/20 [00:00<00:00, 76398.98it/s]
100%|██████████| 20/20 [00:00<00:00, 21361.36it/s]

Current Tech Questions

100%|██████████| 326/326 [00:00<00:00, 459920.32it/s]
100%|██████████| 326/326 [00:00<00:00, 466192.67it/s]
100%|██████████| 326/326 [00:00<00:00, 245131.43it/s]
100%|██████████| 326/326 [00:00<00:00, 435182.40it/s]
100%|██████████| 326/326 [00:00<00:00, 289998.54it/s]
100%|██████████| 326/326 [00:00<00:00, 445098.67it/s]
100%|██████████| 326/326 [00:00<00:00, 309774.15it/s]
100%|██████████| 326/326 [00:00<00:00, 231674.53it/s]

Skill Keywords

100%|██████████| 5553/5553 [00:00<00:00, 973458.59it/s]

Student Progress

100%|██████████| 271/271 [00:00<00:00, 437175.53it/s]
100%|██████████| 271/271 [00:00<00:00, 415141.12it/s]
100%|██████████| 271/271 [00:00<00:00, 192392.75it/s]
100%|██████████| 271/271 [00:00<00:00, 218084.49it/s]

In [ ]:
import re

stopwords = {
    "dan","saya","yang","dengan","ke","di","pada","untuk",
    "adalah","ini","basic","advanced","intro","beginner",
    "dasar","program","programming","pemrograman","bahasa",
    "membuat","make","using","menggunakan", "engineer", "juggling", "jarngan", "webflow", "WebPageMaker", "SOAP API"
    "Chai"
}

def clean_text(text):
    # Pastikan text adalah string
    text = str(text)
    text = re.sub(r'[^\w\s/]', ' ', text)
    words = [w for w in text.split() if w.lower() not in stopwords]
    return " ".join(words)

skill_keywords['keyword'] = skill_keywords['keyword'].fillna("").apply(clean_text)

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())

LP + Course

,learning_path_name,course_name,course_level_str,tutorial_title
0,AI Engineer,Belajar Dasar AI,Dasar,Taksonomi AI
1,AI Engineer,Belajar Dasar AI,Dasar,[Story] Machine Learning: Harapan menjadi keny...
2,AI Engineer,Belajar Dasar AI,Dasar,Rangkuman Kelas
3,AI Engineer,Belajar Dasar AI,Dasar,Tipe-Tipe Machine Learning
4,AI Engineer,Belajar Dasar AI,Dasar,Forum Diskusi

Learning Path

   learning_path_id             learning_path_name
0                 1                    AI Engineer
1                 2              Android Developer
2                 3  Back-End Developer JavaScript
3                 4      Back-End Developer Python
4                 5                 Data Scientist

Course

,course_id,learning_path_id,course_name,course_level_str,hours_to_study
0,1,1,Belajar Dasar AI,1,10
1,2,1,Belajar Fundamental Deep Learning,3,110
2,3,1,Belajar Machine Learning untuk Pemula,2,90
3,4,1,Machine Learning Terapan,4,80
4,5,1,Membangun Proyek Deep Learning Tingkat Mahir,4,90

Course Level

   id course_level
0   1        Dasar
1   2       Pemula
2   3     Menengah
3   4        Mahir
4   5  Profesional

Tutorials

   tutorial_id  course_id                                     tutorial_title
0            1          1                                       Taksonomi AI
1            2          1  [Story] Machine Learning: Harapan menjadi keny...
2            3          1                                    Rangkuman Kelas
3            4          1                         Tipe-Tipe Machine Learning
4            5          1                                      Forum Diskusi

Learning Path Answer

,id,name,summary,description,course_difficulty,course_price,technologies,course_type,courseMeta,courseInfo
0,14,Belajar Fundamental Aplikasi Android,Pelajari skill Android dengan kurikulum terlen...,Android merupakan sistem operasi mobile dengan...,Menengah,PAID,Android,Picodiploma,"['140 Jam', '4,84', 'Menengah']","['107 Modul', '41.831 Siswa Terdaftar']"
1,32,Belajar Membangun LINE Chatbot,Belajar membuat chatbot yang menarik pada plat...,LINE merupakan platform komunikasi yang sangat...,Pemula,PAID,"Android,Chatbot,Web",Reguler,"['20 Jam', '4,89', 'Pemula']","['26 Modul', '15.478 Siswa Terdaftar']"
2,51,Belajar Membuat Aplikasi Android untuk Pemula,Buat aplikasi pertamamu pada Android Studio de...,Android merupakan sistem operasi mobile dengan...,Pemula,PAID,Android,Reguler,"['60 Jam', '4,87', 'Pemula']","['49 Modul', '116.344 Siswa Terdaftar']"
3,60,Memulai Pemrograman Dengan Java,Belajar bahasa Java buat kamu yang ingin mempe...,Java merupakan bahasa yang diciptakan oleh Jam...,Dasar,FREE,"Android,Multi Platform",Reguler,"['15 Jam', '4,86', 'Dasar']","['42 Modul', '80.316 Siswa Terdaftar']"
4,80,Memulai Pemrograman dengan Kotlin,"Pelajari dasar bahasa pemrograman, functional ...",Kotlin merupakan bahasa utama yang digunakan d...,"Dasar,Pemula",PAID,"Android,Multi Platform",Reguler,"['50 Jam', '4,84', 'Dasar - Pemula']","['132 Modul', '59.512 Siswa Terdaftar']"

Current Interest Questions

,question_desc,option_text,category
0,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
1,Mana kegiatan yang paling relate denganmu di p...,Baca atau lihat info viral dari berbagai sumber,Artificial Intelligence
2,Mana kegiatan yang paling relate denganmu di p...,Membersihkan kamar,Cloud Computing
3,Mana kegiatan yang paling relate denganmu di p...,Coret-coret atau menulis di buku,Web Development
4,"Jika sedang menghadapi masalah, cara mana yang...",Coba berbagai cara sampai menemukan solusinya,Mobile Development

Current Tech Questions

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
0,Android,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Komponen yang menangani tampilan pengguna,Kelas untuk menyimpan data,Fungsi untuk menjalankan proses di latar belakang,Antarmuka untuk menghubungkan database,Komponen yang menangani tampilan pengguna
1,Android,beginner,Apa fungsi utama dari file AndroidManifest.xml?,Menyimpan data aplikasi,Mendefinisikan struktur dan metadata aplikasi,Mengatur tata letak UI,Mengelola dependensi proyek,Mendefinisikan struktur dan metadata aplikasi
2,Android,beginner,"Dalam konteks Android, apa yang dimaksud denga...",Komponen untuk menyimpan data,Mekanisme untuk navigasi antar Activity,Fungsi untuk menangani error,Framework untuk membuat UI,Mekanisme untuk navigasi antar Activity
3,Android,beginner,Apa perbedaan utama antara LinearLayout dan Re...,"LinearLayout hanya untuk orientasi vertikal, R...","LinearLayout mengatur elemen secara berurutan,...","LinearLayout untuk aplikasi sederhana, Relativ...","Tidak ada perbedaan, keduanya dapat digunakan ...","LinearLayout mengatur elemen secara berurutan,..."
4,Android,beginner,Apa fungsi dari metode onCreate() dalam sebuah...,Menghapus Activity,Menginisialisasi Activity dan memuat layout,Menjalankan proses di background,Mengatur animasi transisi,Menginisialisasi Activity dan memuat layout

Skill Keywords

   id     keyword
0   4  JavaScript
1   9        Java
2  14      Python
3  19      Kotlin
4  24         PHP

Student Progress

,name,email,password,course_name,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
0,Dina Wijaya,dina.wijaya1@example.com,admin,Belajar Membangun Aplikasi Android Native Bagi...,4,0,0,0,4.0,0.0,0.0,0.0
1,Irfan Halim,irfan.halim2@example.com,admin,Belajar Membangun Aplikasi dengan Universal Wi...,10,0,0,0,76.0,0.0,0.0,0.0
2,Hana Pratama,hana.pratama3@example.com,admin,Belajar Fundamental Aplikasi Android,107,1,0,0,1099.0,0.0,163.0,0.0
3,Dina Utama,dina.utama4@example.com,admin,Belajar Fundamental Aplikasi Android,107,0,0,0,1099.0,0.0,163.0,0.0
4,Rafi Santoso,rafi.santoso5@example.com,admin,Belajar Fundamental Aplikasi Android,107,55,0,0,1099.0,0.0,163.0,0.0

1. Rekomendasi roadmap minimal 1 job role dengan 6 sub-skill

In [ ]:
!pip install google-generativeai

In [ ]:
pip install sentence-transformers scikit-learn

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 78, in main
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/__init__.py", line 114, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
^C

In [ ]:
import re
import random
import torch
from sentence_transformers import SentenceTransformer, util
import google.generativeai as genai
import pandas as pd
from difflib import get_close_matches

# Setup Gemini API
genai.configure(api_key="AIzaSyC9IZj0_dZ8nSVwjm6FGo1urmnaZQdJViM")
model = genai.GenerativeModel("models/gemini-2.5-flash")

# Load Embedding Model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Detect Job Role
job_role = learning_path['learning_path_name'].dropna().unique().tolist()

def detect_job_role(user_input, job_role):
    prompt = f"""
    Anda adalah asisten pintar yang bertugas untuk mengklasifikasikan deskripsi pengguna ke job role yang paling tepat.

    Petunjuk:
    1. Analisis deskripsi pengguna secara menyeluruh.
    2. Bandingkan dengan daftar job role berikut, pilih yang paling relevan.
    3. Hanya pilih **satu job role** yang paling cocok.
    4. Jawaban **hanya berupa nama job role**, tanpa penjelasan, tanda kutip, atau teks tambahan.
    5. Jika tidak yakin, pilih job role yang paling mendekati, jangan buat job role baru.

    Job role valid:
    {job_role}

    Deskripsi pengguna:
    "{user_input}"
    """
    response = model.generate_content(prompt)
    return response.text.strip() if response.text else "Unknown"

# Detect Skills
def detect_skills(user_input, job_role, top_k=6):
    prompt = f"""
    Anda adalah AI pakar dalam technical skill assessment untuk berbagai job role IT.

    ATURAN SUPER KETAT:
    1. Hanya ambil skill dari dataset berikut: {skill_keywords}.
    2. Skill harus sesuai job role (bahasa pemrograman, framework, library, library/framework cloud, library/framework yang relevan dengan AI/ML.)
    3. DILARANG: skill generik, teori, platform software/cloud, metodologi, tools non-teknis/desain, version control, platform dan library yang tidak relevan dengan job role.
    4. Untuk job role Gen AI Engineer menggunakan skill yang sama seperti AI Engineer.
    5. Output HARUS EXACT {top_k} skill, pisah koma, tanpa penjelasan.
    Job Role: {job_role}
    User Input: {user_input}

    Output:
    """

    try:
        resp = model.generate_content(prompt)
        raw_items = [s.strip() for s in resp.text.replace("\n", "").split(",") if s.strip()]
    except Exception as e:
        print("LLM gagal:", e)
        raw_items = []

    # Ambil skill yang valid dari dataset saja
    valid_keywords = skill_keywords['keyword'].dropna().tolist()
    filtered = []

    for item in raw_items:
        match = get_close_matches(item, valid_keywords, n=1, cutoff=0.6)
        if match and match[0] not in filtered:
            filtered.append(match[0])

    # Jika kurang dari top_k, isi dengan skill lain dari dataset
    if len(filtered) < top_k:
        remaining = [k for k in valid_keywords if k not in filtered]
        filtered.extend(remaining[:top_k - len(filtered)])

    return filtered[:top_k]


# Ambil pertanyaan dari dataset tech_qs
from difflib import SequenceMatcher
import pandas as pd

def get_questions_for_skill_from_dataset(skill, tech_qs, num_questions=3):
    filtered = tech_qs[tech_qs['question_desc'].str.contains(skill, case=False, na=False)]

    if len(filtered) >= num_questions:
        filtered = filtered.sample(n=num_questions)
    elif len(filtered) == 0:
        return None

    questions = []
    for _, row in filtered.iterrows():
        # Ambil semua opsi
        options = [
            str(row['option_1']).strip(),
            str(row['option_2']).strip(),
            str(row['option_3']).strip(),
            str(row['option_4']).strip()
        ]

        # Format opsi dengan huruf (A. B. C. D.)
        formatted_options = [f"{chr(65+i)}. {opt}" for i, opt in enumerate(options)]

        # Convert correct_answer (text) ke huruf (A/B/C/D)
        if pd.isna(row['correct_answer']):
            answer_letter = None  # Tandai tidak ada jawaban
        else:
            correct_text = str(row['correct_answer']).strip()
            answer_letter = None  # Default

            # Cari exact match dulu (case-insensitive)
            for i, opt in enumerate(options):
                if opt.lower() == correct_text.lower():
                    answer_letter = chr(65 + i)  # 0→A, 1→B, 2→C, 3→D
                    break

            # Jika tidak ketemu, coba fuzzy matching
            if answer_letter is None:
                best_match_idx = 0
                best_similarity = 0

                for i, opt in enumerate(options):
                    similarity = SequenceMatcher(None, opt.lower(), correct_text.lower()).ratio()
                    if similarity > best_similarity:
                        best_similarity = similarity
                        best_match_idx = i

                # Jika similarity > 80%, anggap match
                if best_similarity > 0.8:
                    answer_letter = chr(65 + best_match_idx)
                else:
                    print(f"Warning: Jawaban '{correct_text[:40]}...' tidak ditemukan!")
                    answer_letter = None

        questions.append({
            "question": row['question_desc'],
            "options": formatted_options,
            "answer": answer_letter  # "A"/"B"/"C"/"D" atau None
        })

    return questions


# Generate pertanyaan via Gemini
def generate_questions_gemini(skill, num_questions=3):
    prompt = f"""
    Anda adalah AI pakar pembuat pertanyaan teknologi.

    Buat {num_questions} pertanyaan pilihan ganda terkait skill: "{skill}".
    Setiap pertanyaan harus memiliki 4 opsi jawaban (A, B, C, D), **tanpa menuliskan jawaban benar**.
    Output cukup dalam text biasa, misal:

    1. Pertanyaan?
    A. jawaban1
    B. jawaban2
    C. jawaban3
    D. jawaban4
    """
    try:
        resp = model.generate_content(prompt)
        resp_text = resp.text.strip()

        questions = []
        q = {}
        lines = resp_text.split("\n")
        answer_index_cycle = list(range(4))

        for line in lines:
            line = line.strip()
            if re.match(r"^\d+\.", line):
                question_text = re.sub(r"^\d+\.\s*", "", line).strip()
                if q:
                    if q.get("options"):
                        answer_idx = answer_index_cycle.pop(0)
                        answer_index_cycle.append(answer_idx)
                        q["answer"] = q["options"][answer_idx][0]
                    else:
                        q["answer"] = "A"
                    questions.append(q)
                q = {"question": question_text, "options": [], "answer": "A"}
            elif re.match(r"^[A-D]\.", line):
                q.setdefault("options", []).append(line)
        if q:
            if q.get("options"):
                answer_idx = answer_index_cycle.pop(0)
                answer_index_cycle.append(answer_idx)
                q["answer"] = q["options"][answer_idx][0]
            else:
                q["answer"] = "A"
            questions.append(q)

        return questions[:num_questions]

    except Exception as e:
        print("LLM gagal membuat pertanyaan:", e)
        return []

# Prepare assessment
def prepare_assessment(detected_skills, tech_qs, total_questions=18):
    num_skills = len(detected_skills)
    questions_per_skill = total_questions // num_skills

    assessment = {}
    for skill in detected_skills:
        questions = get_questions_for_skill_from_dataset(skill, tech_qs, num_questions=questions_per_skill)
        if questions is None or len(questions) < questions_per_skill:
            needed = questions_per_skill if questions is None else questions_per_skill - len(questions)
            generated = generate_questions_gemini(skill, num_questions=needed)
            questions = (questions or []) + generated

        for i, q in enumerate(questions):
            q.setdefault("question", "Pertanyaan tidak tersedia")
            q.setdefault("options", ["A. ...", "B. ...", "C. ...", "D. ..."])
            q.setdefault("answer", "A")

        assessment[skill] = questions

    return assessment

# Run assessment
def run_assessment(assessment):
    results = {}

    for skill, questions in assessment.items():
        print(f"\nSkill: {skill}")
        correct_count = 0
        for idx, q in enumerate(questions, 1):
            print(f"\n{idx}. {q['question']}")

            options = q.get('options', ["A. ...", "B. ...", "C. ...", "D. ..."])
            for opt in options:
                print(opt)

            user_answer = input("Jawaban (A/B/C/D): ").strip().upper()
            while user_answer not in ['A','B','C','D']:
                user_answer = input("Jawaban salah. Masukkan A/B/C/D: ").strip().upper()

            if user_answer == q.get('answer','A').upper():
                correct_count += 1

        if correct_count == len(questions):
            level = "Advanced"
        elif correct_count >= len(questions) - 1:
            level = "Intermediate"
        else:
            level = "Beginner"

        results[skill] = {
            "correct": correct_count,
            "total": len(questions),
            "level": level
        }

    return results

# Hasil
user_input = input("Masukkan deskripsi user: ")

job_role_detected = detect_job_role(user_input, job_role)
skills_detected = detect_skills(user_input, job_role_detected, top_k=6)

print("Job Role:", job_role_detected)
print("Skill:", ", ".join(skills_detected))

total_q = int(input("Pilih total pertanyaan (18 atau 36): "))

assessment = prepare_assessment(skills_detected, tech_qs, total_questions=total_q)
results = run_assessment(assessment)

print("\nHasil Assessment")
for skill, res in results.items():
    print(f"{skill}: {res['correct']}/{res['total']} benar, Level: {res['level']}")

Rekomendasi Course

In [ ]:
from collections import Counter

def aggregate_user_level_majority(results):
    # ambil semua level dari results
    levels = [res["level"] for res in results.values()]

    # hitung frekuensi tiap level
    level_count = Counter(levels)

    # cari level yang paling banyak muncul
    most_common_level, count = level_count.most_common(1)[0]

    return most_common_level

final_level = aggregate_user_level_majority(results)
print(f"\nLevel User Berdasarkan Assessment: {final_level}")

In [ ]:
pip install rapidfuzz

In [ ]:
import pandas as pd
import numpy as np
import re
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from rapidfuzz import process, fuzz

# CLEAN TEXT
def clean_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = text.replace("-", " ")
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# LOAD DATA
course = lp_mapping['Course']

learning_path_mapping = {
    1: "AI Engineer",
    2: "Android Developer",
    3: "Back-End Developer JavaScript",
    4: "Back-End Developer Python",
    5: "Data Scientist",
    6: "DevOps Engineer",
    7: "Front-End Web Developer",
    8: "Gen AI Engineer",
    9: "Google Cloud Professional",
    10: "iOS Developer",
    11: "MLOps Engineer",
    12: "Multi-Platform App Developer",
    13: "React Developer"
}

course['learning_path'] = course['learning_path_id'].map(learning_path_mapping)
course['course_level'] = course['course_level_str'].replace({
    1: "Beginner",
    2: "Beginner",
    3: "Intermediate",
    4: "Advanced",
    5: "Advanced"
})

# FUZZY MATCH (langsung ke lp_answer)
def fuzzy_match_into(df_left, df_right, left_col, right_col, threshold=70):

    matched_list = []

    # cari cocokannya
    for value in df_left[left_col]:
        if pd.isna(value):
            matched_list.append(None)
            continue

        match = process.extractOne(
            value,
            df_right[right_col].tolist(),
            scorer=fuzz.token_set_ratio
        )

        if match and match[1] >= threshold:
            matched_list.append(match[0])
        else:
            matched_list.append(None)

    # tambah kolom matched_name langsung ke lp_answer
    df_left['matched_name'] = matched_list

    # merge langsung tanpa copy
    return df_left.merge(
        df_right,
        left_on='matched_name',
        right_on=right_col,
        how='left'
    )

# MERGE (tanpa normalize, tanpa copy)
lp_combined = fuzzy_match_into(
    lp_answer,
    course[['course_name', 'course_level', 'learning_path']],
    left_col='name',
    right_col='course_name',
    threshold=70
)

# COMBINED TEXT
lp_combined['combined_text'] = (
    lp_combined['course_level'].fillna('') + " " +
    lp_combined['learning_path'].fillna('') + " " +
    lp_combined['course_name'].fillna('') + " " +
    lp_combined['description'].fillna('') + " " +
    lp_combined['technologies'].fillna('')
).apply(clean_text)

# LOAD MODEL
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

course_embeddings = model.encode(lp_combined['combined_text'].tolist(), show_progress_bar=True)

# RECOMMEND FUNCTION
def recommend_from_user_job(user_job, user_level=None, top_k=1):

    final_input = f"{user_job} {user_level}" if user_level else user_job
    input_clean = clean_text(final_input)
    user_emb = model.encode([input_clean])

    sim_scores = cosine_similarity(user_emb, course_embeddings).flatten()

    df = lp_combined.copy()
    df['sim'] = sim_scores

    # filter LP
    matched_lp = None
    for lp in learning_path_mapping.values():
        if lp.lower() in user_job.lower():
            matched_lp = lp
            break

    if matched_lp:
        df = df[df['learning_path'] == matched_lp]

    # filter level
    if user_level:
        df = df[df['course_level'].str.lower() == user_level.lower()]
        df = df.sort_values(by="sim", ascending=False).head(top_k)
    return df[['course_name','course_level', 'summary', 'course_price']]

# TEST
user_job = job_role_detected
user_level = final_level

recommend_from_user_job(user_job, user_level)

Tracking progress pengguna berdasarkan email di dataset

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

class HybridLearningRecommender:
    def __init__(self):
        self.content_similarity = None
        self.success_predictor = None
        self.scaler = StandardScaler()
        self.label_encoders = {}

    # DATA PREPARATION
    def prepare_data(self, lp_answer, course, stud_progress, tutorials):
        course_features = lp_answer.copy()
        text_columns = ['technologies', 'course_type', 'course_difficulty', 'summary']

        for col in text_columns:
            if col in course_features.columns:
                course_features[col] = course_features[col].fillna('').astype(str)

        course_features['combined_features'] = (
            course_features['technologies'] + ' ' +
            course_features['course_type'] + ' ' +
            course_features['course_difficulty'] + ' ' +
            course_features['summary']
        )

        course_data = course.copy()

        stud_metrics = stud_progress.copy()
        numeric_cols = ['completed_tutorials', 'active_tutorials', 'exam_score', 'submission_rating']
        for col in numeric_cols:
            if col in stud_metrics.columns:
                stud_metrics[col] = pd.to_numeric(stud_metrics[col], errors='coerce').fillna(0)

        total_tutorials = stud_metrics['completed_tutorials'] + stud_metrics['active_tutorials']
        stud_metrics['completion_rate'] = np.where(
            total_tutorials > 0,
            (stud_metrics['completed_tutorials'] / total_tutorials) * 100,
            0
        )

        stud_metrics = stud_metrics.merge(
            course_data[['course_name', 'course_level_str', 'hours_to_study', 'learning_path_id']],
            on='course_name',
            how='left'
        )

        if 'hours_to_study' in stud_metrics.columns:
            stud_metrics['hours_to_study'] = pd.to_numeric(stud_metrics['hours_to_study'], errors='coerce').fillna(10)

        for col in ['course_level_str', 'course_name']:
            if col in stud_metrics.columns:
                le = LabelEncoder()
                stud_metrics[col] = stud_metrics[col].astype(str)
                stud_metrics[f'{col}_encoded'] = le.fit_transform(stud_metrics[col])
                self.label_encoders[col] = le

        if 'password' not in stud_metrics.columns:
            stud_metrics['password'] = 'N/A'

        return course_features, stud_metrics, course_data

    # CONTENT-BASED MODEL
    def build_content_based_model(self, course_features):
        tfidf = TfidfVectorizer(stop_words='english', max_features=100)
        tfidf_matrix = tfidf.fit_transform(course_features['combined_features'])
        self.content_similarity = cosine_similarity(tfidf_matrix)
        return self.content_similarity

    # COURSE RECOMMENDATION
    def recommend_courses(self, course_name, course_features, course_data, top_n=3):
        current_course = course_data[course_data['course_name'] == course_name]
        if current_course.empty:
            return pd.DataFrame()

        current_level_str = str(current_course.iloc[0]['course_level_str']).strip()
        current_lp_id = current_course.iloc[0]['learning_path_id']

        try:
            current_level_num = int(current_level_str)
        except:
            current_level_num = 0

        same_path_courses = course_data[
            (course_data['learning_path_id'] == current_lp_id) &
            (course_data['course_level_str'].astype(int) > current_level_num) &
            (course_data['course_name'] != course_name)
        ].sort_values('course_level_str')

        level_map = {
            "1": "Dasar",
            "2": "Pemula",
            "3": "Menengah",
            "4": "Mahir",
            "5": "Profesional"
        }

        recommendations = []
        for _, row in same_path_courses.head(top_n).iterrows():
            recommendations.append({
                'name': row['course_name'],
                'course_difficulty': level_map.get(str(row['course_level_str']).strip(), "N/A"),
                'technologies': row.get('technologies', 'N/A'),
                'hours_to_study': row.get('hours_to_study', 'N/A')
            })

        return pd.DataFrame(recommendations)

    # CLASSIFICATION MODEL
    def build_classification_model(self, stud_metrics):
        features = ['completion_rate', 'active_tutorials', 'completed_tutorials',
                    'course_level_str_encoded', 'hours_to_study']

        X = stud_metrics[features].fillna(0)

        y = ((stud_metrics['is_graduated'] == 1) |
             (stud_metrics['exam_score'] > 75)).astype(int)

        if len(y.unique()) == 1:
            normalized_cr = stud_metrics['completion_rate'] / 100
            normalized_exam = stud_metrics['exam_score'] / 100
            weighted = (normalized_cr * 0.5 + normalized_exam * 0.5)
            y = (weighted >= 0.65).astype(int)

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y if len(y.unique()) > 1 else None
        )

        self.success_predictor = RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            random_state=42
        )
        self.success_predictor.fit(X_train, y_train)

        y_train_pred = self.success_predictor.predict(X_train)
        train_accuracy = accuracy_score(y_train, y_train_pred)

        y_test_pred = self.success_predictor.predict(X_test)
        test_accuracy = accuracy_score(y_test, y_test_pred)

        return self.success_predictor, train_accuracy, test_accuracy

    # SUCCESS PROBABILITY
    def predict_success(self, student_data):
        features = ['completion_rate', 'active_tutorials', 'completed_tutorials',
                    'course_level_str_encoded', 'hours_to_study']

        X = student_data[features].fillna(0)
        if len(X) == 0:
            return 0.0

        cr = student_data['completion_rate'].values[0]
        exam = student_data['exam_score'].values[0] if 'exam_score' in student_data else 0
        sr = student_data['submission_rating'].values[0] if 'submission_rating' in student_data else 0

        norm_cr = cr / 100
        norm_exam = exam / 100
        norm_sr = sr / 5

        final_prob = (norm_cr * 0.25) + (norm_exam * 0.35) + (norm_sr * 0.40)

        return min(final_prob, 0.95)

    # LEARNING STRATEGY
    def generate_learning_strategy(self, student_email, stud_metrics, course_features, course_data):
        student = stud_metrics[stud_metrics['email'] == student_email]
        if len(student) == 0:
            return {"error": "Student not found"}

        student = student.iloc[0]
        current_course = student['course_name']

        recommendations = self.recommend_courses(current_course, course_features, course_data, top_n=3)
        recommended_list = recommendations.to_dict('records') if not recommendations.empty else []

        # Pastikan semua kolom ada
        temp_student = stud_metrics[stud_metrics['email'] == student_email].copy()
        for col in ['completion_rate', 'exam_score', 'submission_rating', 'active_tutorials', 'completed_tutorials', 'hours_to_study']:
            if col not in temp_student.columns:
                temp_student[col] = 0

        success_prob = self.predict_success(temp_student)

        adaptive_roadmap = self._generate_adaptive_roadmap(student, success_prob)

        strategy = {
            "student_name": student['name'],
            "email": student_email,
            "password": student.get('password', 'N/A'),
            "current_course": current_course,
            "completion_rate": student.get('completion_rate', 0),
            "exam_score": student.get('exam_score', 0),
            "submission_rating": student.get('submission_rating', 0),
            "success_probability": success_prob,
            "recommended_courses": recommended_list,
            "adaptive_roadmap": adaptive_roadmap
        }
        return strategy

    # ADAPTIVE ROADMAP
    def _generate_adaptive_roadmap(self, student, success_prob):
        cr = student['completion_rate']
        es = student['exam_score']
        sr = student['submission_rating']
        hours_left = student.get('hours_to_study', 10)

        remaining_completion = 100 - cr

        if success_prob >= 0.70:
            weeks_needed = max(1, int((remaining_completion / 100) * hours_left / 10))
            status_label = "Excellent - On Track"
        elif success_prob >= 0.55:
            weeks_needed = max(2, int((remaining_completion / 100) * hours_left / 8))
            status_label = "Good - Minor Adjustments Needed"
        elif success_prob >= 0.40:
            weeks_needed = max(3, int((remaining_completion / 100) * hours_left / 6))
            status_label = "Moderate - Needs Improvement"
        else:
            weeks_needed = max(4, int((remaining_completion / 100) * hours_left / 4))
            status_label = "At Risk - Immediate Action Required"

        roadmap = {
            "current_status": {
                "overall_status": status_label,
                "progress": f"{cr:.0f}% selesai",
                "exam_performance": f"Score: {es:.0f}/100",
                "submission_rating": f"Rating: {sr:.1f}/5"
            },
            "next_steps": [],
            "estimated_completion": f"{weeks_needed} minggu"
        }

        if success_prob >= 0.70:
            roadmap["next_steps"] = [
                "Step 1: Selesaikan modul advanced & final project",
                "Step 2: Ambil certification exam",
                "Step 3: Build portfolio showcase project",
                "Step 4: Siap lanjut ke level berikutnya"
            ]
        elif success_prob >= 0.55:
            roadmap["next_steps"] = [
                "Step 1: Selesaikan modul yang tertinggal (fokus pada weak areas)",
                "Step 2: Review & retake practice exam untuk score >80",
                "Step 3: Tingkatkan submission quality (target rating 4+)",
                "Step 4: Complete semua assignments sebelum deadline"
            ]
        elif success_prob >= 0.40:
            roadmap["next_steps"] = [
                "Step 1: Fokus pada fundamental concepts (review basics)",
                "Step 2: Join study group atau minta bantuan mentor",
                "Step 3: Submit minimal 50% assignments untuk feedback",
                "Step 4: Target 70%+ completion rate dalam 2 minggu"
            ]
        else:
            roadmap["next_steps"] = [
                "Step 1: URGENT - Meet dengan academic advisor",
                "Step 2: Join intensive tutoring sessions",
                "Step 3: Create daily study schedule dengan mentor",
                "Step 4: Consider course retake atau schedule adjustment"
            ]

        insights = []
        if sr < 2:
            insights.append("Submission rating rendah - perlu improve assignment quality")
        if cr < 50:
            insights.append("Completion rate <50% - accelerate learning pace")
        elif cr < 70:
            insights.append("Completion rate moderate - maintain steady progress")
        if es < 70:
            insights.append("Exam score <70 - review fundamental concepts")
        elif es >= 90:
            insights.append("Excellent exam performance - strong understanding!")
        if sr == 0:
            insights.append("Belum ada submission - mulai kerjakan assignments!")

        if es >= 90 and cr < 60:
            insights.append("High exam score but low completion - focus on finishing modules!")
        if cr >= 80 and es < 60:
            insights.append("High completion but low exam - review concepts more deeply!")

        roadmap["insights"] = insights if insights else ["Keep up the good work!"]

        return roadmap

# MAIN FUNCTION
def main(lp_answer, course, stud_progress, tutorials):
    recommender = HybridLearningRecommender()
    course_features, stud_metrics, course_data = recommender.prepare_data(lp_answer, course, stud_progress, tutorials)
    recommender.build_content_based_model(course_features)
    model, train_acc, test_acc = recommender.build_classification_model(stud_metrics)

    return recommender, stud_metrics, course_features, course_data, train_acc, test_acc

# RUNNING OUTPUT
recommender, stud_metrics, course_features, course_data, train_acc, test_acc = main(
    lp_answer, course, stud_progress, tutorials
)

print(f"Training Accuracy: {train_acc*100:.2f}%")
print(f"Testing Accuracy: {test_acc*100:.2f}%")

# PRINT STUDENT RESULTS
for email in stud_metrics['email'].unique():
    strategy = recommender.generate_learning_strategy(
        email, stud_metrics, course_features, course_data
    )

    print(f"\n{'='*70}")
    print(f"👤 Student: {strategy['student_name']} ({strategy['email']})")
    print(f"{'='*70}")

    print(f"\nCurrent Course:")
    print(f"  - {strategy['current_course']}")

    print(f"\nCurrent Status:")
    print(f"  - Completion Rate: {strategy['completion_rate']:.1f}%")
    print(f"  - Exam Score: {strategy['exam_score']:.0f}/100")
    print(f"  - Submission Rating: {strategy['submission_rating']:.1f}/5")
    print(f"  - Success Probability: {strategy['success_probability']*100:.1f}%")
    print(f"  - Overall Status: {strategy['adaptive_roadmap']['current_status']['overall_status']}")

    print(f"\nRecommended Next Courses:")
    if strategy['recommended_courses']:
        for i, course_rec in enumerate(strategy['recommended_courses'], 1):
            duration = f" ({course_rec['hours_to_study']}h)" if course_rec['hours_to_study'] != 'N/A' else ""
            print(f"  {i}. {course_rec['name']} ({course_rec['course_difficulty']}) - Duration{duration}")
    else:
        print("Tidak ada rekomendasi")

    print(f"\nLearning Roadmap:")
    for i, step in enumerate(strategy['adaptive_roadmap']['next_steps'], 1):
        print(f"  {i}. {step}")

    print(f"\nEstimated Completion: {strategy['adaptive_roadmap']['estimated_completion']}")

    if strategy['adaptive_roadmap']['insights']:
        print(f"\nKey Insights:")
        for insight in strategy['adaptive_roadmap']['insights']:
            print(f"  - {insight}")

Streaming output truncated to the last 5000 lines.

======================================================================
👤 Student: Lestari Ramadhan (lestari.ramadhan113@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 0.0%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 0.0%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Qori Ramadhan (qori.ramadhan114@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 46.8%
  - Exam Score: 93/100
  - Submission Rating: 0.0/5
  - Success Probability: 44.2%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 3 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Excellent exam performance - strong understanding!
  - Belum ada submission - mulai kerjakan assignments!
  - High exam score but low completion - focus on finishing modules!

======================================================================
👤 Student: Dina Halim (dina.halim115@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 46.8%
  - Exam Score: 80/100
  - Submission Rating: 0.0/5
  - Success Probability: 39.7%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Hana Santoso (hana.santoso116@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 46.8%
  - Exam Score: 93/100
  - Submission Rating: 0.0/5
  - Success Probability: 44.2%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 3 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Excellent exam performance - strong understanding!
  - Belum ada submission - mulai kerjakan assignments!
  - High exam score but low completion - focus on finishing modules!

======================================================================
👤 Student: Kiki Wijaya (kiki.wijaya117@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 13.2%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 3.3%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Sari Saputra (sari.saputra118@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 17.5%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 4.4%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Hana Gunawan (hana.gunawan119@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 6.6%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 1.7%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Hana Wijaya (hana.wijaya120@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 46.8%
  - Exam Score: 93/100
  - Submission Rating: 0.0/5
  - Success Probability: 44.2%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 3 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Excellent exam performance - strong understanding!
  - Belum ada submission - mulai kerjakan assignments!
  - High exam score but low completion - focus on finishing modules!

======================================================================
👤 Student: Citra Hartono (citra.hartono121@example.com)
======================================================================

Current Course:
  - Belajar Dasar Cloud dan Gen AI di AWS

Current Status:
  - Completion Rate: 46.8%
  - Exam Score: 80/100
  - Submission Rating: 0.0/5
  - Success Probability: 39.7%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Bima Halim (bima.halim122@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 0.0%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 0.0%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 11 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Citra Prasetyo (citra.prasetyo123@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 37.6%
  - Exam Score: 93/100
  - Submission Rating: 0.0/5
  - Success Probability: 42.0%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Excellent exam performance - strong understanding!
  - Belum ada submission - mulai kerjakan assignments!
  - High exam score but low completion - focus on finishing modules!

======================================================================
👤 Student: Bima Wibowo (bima.wibowo124@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 19.6%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 4.9%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 9 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Kiki Santoso (kiki.santoso125@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 27.5%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 6.9%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 8 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Qori Halim (qori.halim126@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 40.0%
  - Exam Score: 90/100
  - Submission Rating: 0.0/5
  - Success Probability: 41.5%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Excellent exam performance - strong understanding!
  - Belum ada submission - mulai kerjakan assignments!
  - High exam score but low completion - focus on finishing modules!

======================================================================
👤 Student: Irfan Utama (irfan.utama127@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 39.7%
  - Exam Score: 86/100
  - Submission Rating: 0.0/5
  - Success Probability: 40.0%
  - Overall Status: Moderate - Needs Improvement

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: Fokus pada fundamental concepts (review basics)
  2. Step 2: Join study group atau minta bantuan mentor
  3. Step 3: Submit minimal 50% assignments untuk feedback
  4. Step 4: Target 70%+ completion rate dalam 2 minggu

Estimated Completion: 4 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Putu Halim (putu.halim128@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 35.8%
  - Exam Score: 0/100
  - Submission Rating: 0.0/5
  - Success Probability: 9.0%
  - Overall Status: At Risk - Immediate Action Required

Recommended Next Courses:
  1. Belajar Back-End Pemula dengan JavaScript (Pemula) - Duration (50h)
  2. Architecting on AWS (Membangun Arsitektur Cloud di AWS) (Menengah) - Duration (40h)
  3. Belajar Fundamental Back-End dengan JavaScript (Menengah) - Duration (90h)

Learning Roadmap:
  1. Step 1: URGENT - Meet dengan academic advisor
  2. Step 2: Join intensive tutoring sessions
  3. Step 3: Create daily study schedule dengan mentor
  4. Step 4: Consider course retake atau schedule adjustment

Estimated Completion: 7 minggu

Key Insights:
  - Submission rating rendah - perlu improve assignment quality
  - Completion rate <50% - accelerate learning pace
  - Exam score <70 - review fundamental concepts
  - Belum ada submission - mulai kerjakan assignments!

======================================================================
👤 Student: Rafi Pratama (rafi.pratama129@example.com)
======================================================================

Current Course:
  - Belajar Dasar Pemrograman JavaScript

Current Status:
  - Completion Rate: 40.0%
  - Exam Score: 90/100
  - Submission Rating: 0.0/5

Berdasarkan skill

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.ensemble import RandomForestClassifier
import re

# LOAD DATA
df = pd.read_csv("Skill.csv").fillna("")
level_order = {"Beginner": 1, "Intermediate": 2, "Advanced": 3}
df["level_num"] = df["skill_level"].map(level_order)

# TF-IDF
df["skill_text"] = df["skill"] + " " + df["description"]
tfidf = TfidfVectorizer()
skill_tfidf = tfidf.fit_transform(df["skill_text"])

df["lp_text"] = df["learning_path_name"] + " " + df["skill_text"]
lp_tfidf = tfidf.fit_transform(df["lp_text"])

# HELPER FUNCTIONS
def parse_prereq(prereq):
    if prereq == "":
        return []
    text = prereq.lower()
    text = re.sub(r" and |&|\+|/|;", ",", text)
    parts = [p.strip() for p in text.split(",") if p.strip()]
    return parts

def match_skill(token):
    token = token.lower()
    for s in df["skill"].str.lower():
        s_clean = s.split("(")[0].strip()
        if token == s_clean or token in s_clean or s_clean in token:
            return s_clean
    return None

def detect_learning_path(query):
    q_vec = tfidf.transform([query])
    lp_scores = {}
    for lp in df["learning_path_name"].unique():
        lp_skills = df[df["learning_path_name"] == lp]
        lp_vec = tfidf.transform(lp_skills["skill_text"])
        sims = cosine_similarity(q_vec, lp_vec).max()
        lp_scores[lp] = sims
    best_lp = max(lp_scores, key=lp_scores.get)
    return best_lp

# MULTI-CURRENT SKILL DETECTION
def find_current_skill(query):
    lp = detect_learning_path(query)
    df_filtered = df[df["learning_path_name"] == lp].copy()
    q_lower = query.lower()
    for s in df_filtered["skill"].str.lower():
        s_clean = s.split("(")[0].strip()
        if re.search(r"\b" + re.escape(s_clean) + r"\b", q_lower):
            return df_filtered[df_filtered["skill"].str.lower() == s].iloc[0]
    return df_filtered.iloc[df_filtered["level_num"].idxmin()]

def find_current_skills(query):
    lp = detect_learning_path(query)
    df_filtered = df[df["learning_path_name"] == lp].copy()
    query_lower = query.lower()
    matched_skills = []

    for s in df_filtered["skill"].str.lower():
        s_clean = s.split("(")[0].strip()
        if re.search(r"\b" + re.escape(s_clean) + r"\b", query_lower):
            matched_skills.append(df_filtered[df_filtered["skill"].str.lower() == s].iloc[0])

    if not matched_skills:
        matched_skills.append(find_current_skill(query))

    print(f"Detected Learning Path: {lp}")
    print(f"Detected Current Skills: {[s['skill'] for s in matched_skills]}")
    return matched_skills

# TRAINING
pairs = []
for _, row in df.iterrows():
    curr = row["skill"]
    curr_level = row["level_num"]
    prereq_tokens = parse_prereq(row["prerequisite"])
    if not prereq_tokens:
        continue
    for p in prereq_tokens:
        matched_skill = match_skill(p)
        if matched_skill is None:
            continue
        parent_rows = df[df["skill"].str.lower().str.startswith(matched_skill)]
        if parent_rows.empty:
            continue
        parent = parent_rows.iloc[0]
        pairs.append({
            "current_skill": parent["skill"],
            "next_skill": curr,
            "current_level": parent["level_num"],
            "next_level": curr_level,
            "is_prerequisite": 1
        })

positive_pairs = pd.DataFrame(pairs)
neg_pairs = []
for _ in range(len(positive_pairs)):
    sample = df.sample(2).reset_index(drop=True)
    a = sample.iloc[0]
    b = sample.iloc[1]
    neg_pairs.append({
        "current_skill": a["skill"],
        "next_skill": b["skill"],
        "current_level": a["level_num"],
        "next_level": b["level_num"],
        "is_prerequisite": 0
    })

negative_pairs = pd.DataFrame(neg_pairs)
pairs_df = pd.concat([positive_pairs, negative_pairs]).reset_index(drop=True)

# FEATURE EXTRACTION & TRAINING
X_features = []
y_labels = pairs_df["is_prerequisite"].values
for _, row in pairs_df.iterrows():
    curr_idx = df[df["skill"] == row["current_skill"]].index[0]
    next_idx = df[df["skill"] == row["next_skill"]].index[0]
    sim = cosine_similarity(skill_tfidf[curr_idx], skill_tfidf[next_idx])[0][0]
    X_features.append([
        sim,
        row["next_level"] - row["current_level"],
        row["current_level"],
        row["next_level"],
    ])

X = np.array(X_features)
y = y_labels

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=120,
    max_depth=7,
    min_samples_split=4,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
print(f"Train accuracy: {rf_model.score(X_train, y_train):.3f}")
print(f"Test accuracy: {rf_model.score(X_test, y_test):.3f}")

# PREDICT NEXT SKILLS
def predict_next_skills(query, top_n=5):
    current_skills = find_current_skills(query)
    all_predictions = []

    current_skill_names = set()
    for curr in current_skills:
        skill_lower = curr["skill"].lower().split("(")[0].strip()
        current_skill_names.add(skill_lower)

    lp = current_skills[0]["learning_path_name"]
    max_curr_level = max(curr["level_num"] for curr in current_skills)

    lp_skills = df[df["learning_path_name"] == lp].copy()

    def prereqs_satisfied(row):
        prereq_tokens = parse_prereq(row["prerequisite"])
        if not prereq_tokens:
            return False

        matched_prereqs = set()
        for token in prereq_tokens:
            matched = match_skill(token)
            if matched:
                matched_prereqs.add(matched)

        if len(matched_prereqs) == 0:
            return False

        matched_count = 0
        for curr_name in current_skill_names:
            for prereq in matched_prereqs:
                if curr_name in prereq or prereq in curr_name:
                    matched_count += 1
                    break

        if len(current_skill_names) == 1:
            return matched_count >= 1
        else:
            return matched_count == len(current_skill_names)

    candidates = lp_skills[lp_skills.apply(prereqs_satisfied, axis=1)]
    candidates = candidates[candidates["level_num"] >= max_curr_level]

    for _, cand in candidates.iterrows():
        next_idx = cand.name
        similarities = []

        for curr in current_skills:
            curr_idx = curr.name
            sim = cosine_similarity(skill_tfidf[curr_idx], skill_tfidf[next_idx])[0][0]
            similarities.append(sim)

        avg_sim = np.mean(similarities)
        features = np.array([[avg_sim, cand["level_num"] - max_curr_level, max_curr_level, cand["level_num"]]])
        prob = rf_model.predict_proba(features)[0][1]

        level_boost = 1.0
        if cand["level_num"] == max_curr_level + 1:
            level_boost = 1.2
        elif cand["level_num"] == max_curr_level:
            level_boost = 1.1

        all_predictions.append({
            "skill": cand["skill"],
            "skill_level": cand["skill_level"],
            "prerequisite": cand["prerequisite"],
            "probability": prob * level_boost,
            "level_num": cand["level_num"]
        })

    if not all_predictions:
        return pd.DataFrame()

    result_df = pd.DataFrame(all_predictions)

    # HITUNG TOTAL PREREQUISITE SKILL
    result_df["total_prereq"] = result_df["prerequisite"].apply(lambda x: len(parse_prereq(x)))

    # Urutkan: 1) level ascending, 2) total prerequisite ascending, 3) probability descending
    result_df = result_df.sort_values(
        ["level_num", "total_prereq", "probability"],
        ascending=[True, True, False]
    )

    result_df = result_df.drop(columns=["level_num", "total_prereq"])
    result_df = result_df.drop_duplicates(subset=["skill"])
    return result_df.head(top_n)

# TESTING
test_queries = [
    "sehabis HTML, apa lagi yang harus dipelajari untuk jadi web developer?",
    "sehabis JavaScript, apa lagi yang harus dipelajari untuk jadi Front-End Web Developer?",
    "sehabis React, apa lagi yang harus dipelajari untuk jadi React Developer?",
    "sehabis Python, Matplotlib, apa lagi yang harus dipelajari untuk jadi Data Scientist?"
]

for q in test_queries:
    print(f"Query: {q}")
    result = predict_next_skills(q, top_n=5)
    if not result.empty:
        print(result.to_string(index=False))
    else:
        print("No recommendations found.")
    print()

Train accuracy: 0.825
Test accuracy: 0.725
Query: sehabis HTML, apa lagi yang harus dipelajari untuk jadi web developer?
Detected Learning Path: Front-End Web Developer
Detected Current Skills: ['HTML (Markup Language)']
                            skill skill_level prerequisite  probability
             CSS (Style Language)    Beginner         HTML     0.991070
JavaScript (Programming Language)    Beginner    HTML, CSS     1.087223

Query: sehabis JavaScript, apa lagi yang harus dipelajari untuk jadi Front-End Web Developer?
Detected Learning Path: Front-End Web Developer
Detected Current Skills: ['JavaScript (Programming Language)']
                          skill  skill_level    prerequisite  probability
  NPM (Package Management Tool)     Beginner      JavaScript     0.657449
   Axios (HTTP Request Library) Intermediate      JavaScript     0.673543
React (JavaScript Framework UI) Intermediate JavaScript, NPM     1.016590
    Vite (Front-End Build Tool) Intermediate JavaScript, NPM     0.738992
  Webpack (Module Bundler Tool)     Advanced JavaScript, NPM     0.348556

Query: sehabis React, apa lagi yang harus dipelajari untuk jadi React Developer?
Detected Learning Path: React Developer
Detected Current Skills: ['React (Framework UI)']
                                   skill  skill_level prerequisite  probability
     Styled Components (Library Styling) Intermediate        React     0.998395
          React Router (Library Routing) Intermediate        React     0.959391
      Zustand (Library State Management) Intermediate        React     0.772266
Redux Toolkit (Library State Management) Intermediate        React     0.748177
     React Query (Library Data Fetching)     Advanced React, Axios     0.866270

Query: sehabis Python, Matplotlib, apa lagi yang harus dipelajari untuk jadi Data Scientist?
Detected Learning Path: Data Scientist
Detected Current Skills: ['Python (Programming Language)', 'Matplotlib (Visualization Library)']
                          skill skill_level       prerequisite  probability
Seaborn (Visualization Library)    Beginner Python, Matplotlib     1.087223

Saran strategi belajar

In [ ]:
!pip install google-generativeai

In [ ]:
import json
import pandas as pd
import google.generativeai as genai

# Load data.json
with open("data.json", "r") as f:
    data = json.load(f)

resources = data["resources"]

# Setup LLM Gemini
genai.configure(api_key="AIzaSyC9IZj0_dZ8nSVwjm6FGo1urmnaZQdJViM")
model = genai.GenerativeModel("models/gemini-2.5-flash")

# Fungsi Generate Strategi Belajar
def generate_actionable_learning_strategy(next_skills, goal=None):
    next_text = ", ".join(next_skills)

    level_nums = []
    for skill in next_skills:
        row = df[df["skill"] == skill]
        if not row.empty:
            level_nums.append(row["level_num"].iloc[0])
    level_num = min(level_nums) if level_nums else 1

    # Ambil maksimal 2 resource per skill
    references_text = ""
    for i, skill in enumerate(next_skills, start=1):
        # Filter resource yang judulnya mengandung skill (jika field skill tidak ada)
        skill_resources = [r for r in resources if skill.lower() in r.get("title", "").lower()][:2]
        if skill_resources:
            references_text += f"{i}. {skill}:\n"
            for r in skill_resources:
                references_text += f"  - {r['title']} ({r['type']})\n    {r['url']}\n"

    prompt = f"""
Kamu adalah mentor belajar yang praktis dan terstruktur. Gunakan bahasa yang tidak terlalu baku, semangat, ramah, dan ceria.
Buat strategi belajar harian untuk seseorang yang ingin mempelajari skill: {next_text} {f"dengan tujuan akhir: {goal}" if goal else ""}.
Berikan saran output subskill berdasarkan level skill yang sudah terdeteksi: {level_nums}.
Format output harus persis seperti ini.
Yuk naikin skill kamu! Ini rencana belajar yang bakal nge-boost perkembanganmu! ⚡
1️. <Nama Skill>:
  - <Subskill>
  - <Subskill>
  - <Subskill>
  dst.

Tips seru supaya belajar makin efektif 💡
(Pilih 3 tips belajar secara acak. Harus berikan 1 tips teknik belajar populer.
Tips boleh berasal dari kebiasaan belajar, trik fokus, pengaturan lingkungan, manajemen waktu, mindset positif, atau cara mencatat yang efektif.
Setiap tips harus sangat singkat, maksimal 2 kalimat pendek, tidak lebih dari 10 kata.)
- <Tips 1>
- <Tips 2>
- <Tips 3>

Referensi buat kamu 📚
(Resource yang dikeluarkan hanya berdasarkan skill: {next_text}. Dilarang menambahkan resource selain di sini)
{references_text}

Berikut roadmap belajar mingguanmu 😉
Atur jadwal sesuai aturan berikut:
1. Fokus pada satu skill utama terlebih dahulu sebelum pindah ke skill berikutnya.
2. Jika dalam satu hari hanya ada 1 subskill → berikan 1 durasi belajar (durasi bebas).
3. Jika dalam satu hari ada lebih dari 1 subskill → berikan durasi untuk masing-masing subskill (setiap durasi bebas).
4. Durasi belajar harus realistis dan logis berdasarkan tingkat kesulitan subskill.
5. Durasi belajar menggunakan format lama waktu, bukan jam pada pukul tertentu.
Durasi belajar harus dalam format lama waktu saja: "45 menit", "1 jam", "90 menit", "2 jam", dst. Tidak boleh menggunakan kombinasi jam + menit (misal: "1 jam 30 menit" dilarang).
Format jadwal harus persis seperti ini:
- Hari 1: <Durasi 1> → <Skill>: <Subskill 1>
  Hari 1: <Durasi 2> → <Skill>: <Subskill 2> (jika ada)
- Hari 2: <Durasi> → <Skill>: <Subskill>
dst.
"""
    response = model.generate_content(prompt)
    return response.text

# Full Pipeline Example
query = "sehabis css, apa lagi yang harus dipelajari untuk jadi front-end web developer?"
next_skills_df = predict_next_skills(query, top_n=5)

if not next_skills_df.empty:
    next_skills = [s.split("(")[0].strip() for s in next_skills_df["skill"].tolist()]
    strategy = generate_actionable_learning_strategy(next_skills)
    print(strategy.replace("**", ""))
else:
    print("No next skill recommendations found.")

Detected Learning Path: Front-End Web Developer
Detected Current Skills: ['CSS (Style Language)']
Yuk naikin skill kamu! Ini rencana belajar yang bakal nge-boost perkembanganmu! ⚡

1️. JavaScript:
  - Dasar-dasar Sintaks, Variabel, dan Tipe Data
  - Operator dan Struktur Kontrol (if/else, loop)
  - Fungsi dan Scope
  - Array dan Object
  - DOM Manipulation Dasar
  - Event Handling Sederhana
  - Proyek Mini JS (misal: Kalkulator Sederhana)

2️. Tailwind CSS:
  - Pengenalan Tailwind & Setup Proyek
  - Konsep Utility-First & Dasar Styling (Warna, Teks, Spasi)
  - Layouting dengan Flexbox & Grid (Dasar)
  - Responsive Design (Breakpoints)
  - Membuat Komponen UI Dasar (Button, Card)
  - Proyek Mini Tailwind (misal: Landing Page Statis)

Tips seru supaya belajar makin efektif 💡
- Teknik Pomodoro. Fokus 25 menit, istirahat 5. Produktivitasmu pasti naik!
- Praktik Langsung. Jangan cuma baca, langsung ketik kode. Lebih cepat paham!
- Istirahat Teratur. Otak butuh jeda, jangan maraton. Belajar jadi awet!

Referensi buat kamu 📚
1. JavaScript:
  - Learn JavaScript - Full Course for Beginners (Video)
    https://www.youtube.com/watch?v=PkZNo7MFNFg
  - SESI 7 - Javascript Backend (Node JS) Untuk Pemula (Video)
    https://www.youtube.com/watch?v=kLUI9LISP5k
2. Tailwind CSS:
  - Tailwind CSS Crash Course (Video)
    https://www.youtube.com/watch?v=dFgzHOX84xQ
  - Tailwind CSS Official Getting Started (Web)
    https://tailwindcss.com/docs/installation

Berikut roadmap belajar mingguanmu 😉
- Hari 1: 90 menit → JavaScript: Dasar-dasar Sintaks, Variabel, dan Tipe Data
  Hari 1: 60 menit → JavaScript: Operator dan Struktur Kontrol (if/else, loop)
- Hari 2: 90 menit → JavaScript: Fungsi dan Scope
  Hari 2: 90 menit → JavaScript: Array dan Object
- Hari 3: 2 jam → JavaScript: DOM Manipulation Dasar
  Hari 3: 1 jam → JavaScript: Event Handling Sederhana
- Hari 4: 2 jam → JavaScript: Proyek Mini JS (misal: Kalkulator Sederhana)
- Hari 5: 1 jam → Tailwind CSS: Pengenalan Tailwind & Setup Proyek
  Hari 5: 90 menit → Tailwind CSS: Konsep Utility-First & Dasar Styling (Warna, Teks, Spasi)
- Hari 6: 2 jam → Tailwind CSS: Layouting dengan Flexbox & Grid (Dasar)
  Hari 6: 90 menit → Tailwind CSS: Responsive Design (Breakpoints)
- Hari 7: 2 jam → Tailwind CSS: Membuat Komponen UI Dasar (Button, Card)
  Hari 7: 1 jam → Tailwind CSS: Proyek Mini Tailwind (misal: Landing Page Statis)